// ── V7.1.8 Design RAG — Design Corpus ────────────────────────────────────────
// 104 design references seeded from registry templates and premium patterns.

export type DesignCategory =
  | 'hero' | 'features' | 'pricing' | 'testimonials'
  | 'dashboard' | 'faq' | 'cta' | 'navbar';

export type DesignStyle =
  | 'linear' | 'stripe' | 'vercel' | 'framer' | 'notion' | 'apple'
  | 'cursor' | 'raycast';

export interface DesignReference {
  id: string;
  category: DesignCategory;
  industry: string[];
  style: DesignStyle[];
  layout: string;
  tags: string[];
  description: string;
  componentIds: string[];
  qualityHint: number; // 0–10 baseline quality estimate
}

// ── HERO — 25 references ──────────────────────────────────────────────────────
const heroRefs: DesignReference[] = [
  {
    id: 'hero-saas-centered',
    category: 'hero',
    industry: ['saas', 'startup', 'productivity', 'ai'],
    style: ['vercel', 'linear'],
    layout: 'centered',
    tags: ['centered', 'h1-large', 'dual-cta', 'badge', 'gradient-text'],
    description: 'Centered headline with gradient text, badge pill above title, primary + outline dual CTA, social proof strip below.',
    componentIds: ['hero-saas-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'hero-split-visual',
    category: 'hero',
    industry: ['saas', 'enterprise', 'analytics', 'fintech'],
    style: ['stripe', 'linear'],
    layout: 'split-layout',
    tags: ['split', 'product-visual', 'left-copy', 'right-screenshot'],
    description: 'Left text block with headline and dual CTA, right product screenshot or 3D mockup with subtle shadow.',
    componentIds: ['hero-split-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'hero-bento-grid',
    category: 'hero',
    industry: ['saas', 'ai', 'developer', 'productivity'],
    style: ['framer', 'linear'],
    layout: 'bento',
    tags: ['bento', 'grid', 'visual-cards', 'asymmetric', 'animated'],
    description: 'Asymmetric bento grid below centered headline. Cards showcase product features with micro-animations.',
    componentIds: ['hero-bento-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'hero-editorial-large',
    category: 'hero',
    industry: ['agency', 'media', 'startup', 'developer'],
    style: ['linear', 'vercel'],
    layout: 'editorial-large',
    tags: ['large-type', 'editorial', 'minimal', 'word-highlight'],
    description: 'Oversized editorial headline spanning full width. Minimal decoration, single powerful CTA, strong typographic hierarchy.',
    componentIds: ['hero-editorial-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'hero-gradient-premium',
    category: 'hero',
    industry: ['fintech', 'enterprise', 'saas', 'security'],
    style: ['stripe', 'framer'],
    layout: 'centered-gradient',
    tags: ['gradient-bg', 'mesh-gradient', 'premium', 'enterprise', 'trust-signals'],
    description: 'Full-bleed mesh gradient background, centered headline, logo cloud trust strip, stat metrics below CTA.',
    componentIds: ['hero-premium-v1'],
    qualityHint: 9.3,
  },
  {
    id: 'hero-glassmorphism',
    category: 'hero',
    industry: ['ai', 'startup', 'tech', 'gaming'],
    style: ['framer', 'cursor'],
    layout: 'centered',
    tags: ['glass', 'blur', 'floating-ui', 'neon-accent', 'dark'],
    description: 'Dark backdrop with glassmorphism floating UI panels, glowing accent borders, animated particle or grid background.',
    componentIds: ['hero-glass-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'hero-minimal-white',
    category: 'hero',
    industry: ['health', 'legal', 'finance', 'consulting'],
    style: ['notion', 'apple'],
    layout: 'centered',
    tags: ['light', 'minimal', 'clean', 'professional', 'whitespace'],
    description: 'Light background, clean serif or sans headline, single primary CTA, customer logo trust bar below.',
    componentIds: ['hero-minimal-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'hero-video-background',
    category: 'hero',
    industry: ['agency', 'travel', 'media', 'gaming'],
    style: ['framer', 'apple'],
    layout: 'fullscreen',
    tags: ['video-bg', 'fullscreen', 'overlay', 'motion'],
    description: 'Full-viewport video or animated canvas background, dark overlay, large centered white text and single CTA.',
    componentIds: ['hero-video-v1'],
    qualityHint: 8.2,
  },
  {
    id: 'hero-announcement-bar',
    category: 'hero',
    industry: ['saas', 'startup', 'ecommerce', 'productivity'],
    style: ['linear', 'vercel'],
    layout: 'centered',
    tags: ['announcement', 'badge', 'changelog', 'new-feature'],
    description: 'Centered hero with announcement pill or badge linking to new feature/changelog above the headline.',
    componentIds: ['hero-announce-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'hero-terminal-code',
    category: 'hero',
    industry: ['developer', 'saas', 'devtools', 'security'],
    style: ['vercel', 'linear'],
    layout: 'split-layout',
    tags: ['terminal', 'code-block', 'developer', 'cli', 'dark'],
    description: 'Left headline and CTA, right animated terminal / code block showing product in use.',
    componentIds: ['hero-terminal-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'hero-dashboard-preview',
    category: 'hero',
    industry: ['analytics', 'saas', 'crm', 'fintech'],
    style: ['linear', 'stripe'],
    layout: 'split-layout',
    tags: ['dashboard-preview', 'product-screenshot', 'browser-frame'],
    description: 'Centered or split layout with browser-framed dashboard screenshot floating below the headline with drop shadow.',
    componentIds: ['hero-dashboard-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'hero-startup-bold',
    category: 'hero',
    industry: ['startup', 'ai', 'consumer', 'social'],
    style: ['framer', 'raycast'],
    layout: 'centered',
    tags: ['bold', 'color-pop', 'large-cta', 'vibrant'],
    description: 'Bold vibrant headline with color word highlight, large pill CTA, floating feature preview cards around it.',
    componentIds: ['hero-bold-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'hero-ecommerce-collection',
    category: 'hero',
    industry: ['ecommerce', 'fashion', 'retail', 'consumer'],
    style: ['apple', 'notion'],
    layout: 'split-layout',
    tags: ['product-image', 'collection', 'shop-now', 'imagery'],
    description: 'Product imagery dominant, concise headline, shop-now CTA with category pills or collection grid.',
    componentIds: ['hero-ecom-v1'],
    qualityHint: 8.4,
  },
  {
    id: 'hero-mobile-app',
    category: 'hero',
    industry: ['mobile', 'consumer', 'health', 'social'],
    style: ['apple', 'framer'],
    layout: 'centered',
    tags: ['app-store', 'mobile-preview', 'rating', 'download'],
    description: 'Centered headline with App Store / Play Store CTA badges, device mockup showing mobile app screenshot.',
    componentIds: ['hero-mobile-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'hero-countdown-launch',
    category: 'hero',
    industry: ['startup', 'ecommerce', 'consumer', 'saas'],
    style: ['framer', 'raycast'],
    layout: 'centered',
    tags: ['countdown', 'launch', 'waitlist', 'scarcity'],
    description: 'Coming-soon style with countdown timer, email waitlist CTA, animated background.',
    componentIds: ['hero-countdown-v1'],
    qualityHint: 8.3,
  },
  {
    id: 'hero-portfolio',
    category: 'hero',
    industry: ['agency', 'freelance', 'design', 'creative'],
    style: ['notion', 'vercel'],
    layout: 'editorial-large',
    tags: ['portfolio', 'personal', 'creative', 'work-gallery'],
    description: 'Personal or agency portfolio hero with name, role descriptor, featured work grid below.',
    componentIds: ['hero-portfolio-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'hero-social-proof-centric',
    category: 'hero',
    industry: ['saas', 'health', 'education', 'consumer'],
    style: ['stripe', 'notion'],
    layout: 'centered',
    tags: ['social-proof', 'avatars', 'stars', 'ratings-central'],
    description: 'Hero where social proof (star ratings, avatar stack, user count) is prominently placed directly below headline.',
    componentIds: ['hero-social-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'hero-enterprise-blue',
    category: 'hero',
    industry: ['enterprise', 'security', 'compliance', 'b2b'],
    style: ['stripe', 'linear'],
    layout: 'centered',
    tags: ['enterprise', 'trust', 'blue', 'compliance', 'professional'],
    description: 'Conservative enterprise design: blue tones, certification badges, partner logos, demo request CTA.',
    componentIds: ['hero-enterprise-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'hero-fintech-dark',
    category: 'hero',
    industry: ['fintech', 'crypto', 'banking', 'payments'],
    style: ['linear', 'cursor'],
    layout: 'split-layout',
    tags: ['fintech', 'dark', 'numbers', 'metrics', 'trust'],
    description: 'Dark fintech hero with live metric counters, split layout showing financial dashboard or chart.',
    componentIds: ['hero-fintech-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'hero-edtech-bright',
    category: 'hero',
    industry: ['edtech', 'education', 'learning', 'courses'],
    style: ['notion', 'apple'],
    layout: 'centered',
    tags: ['edtech', 'bright', 'students', 'learning', 'curriculum'],
    description: 'Bright accessible hero with student outcomes, course preview card, enrollment CTA with rating.',
    componentIds: ['hero-edtech-v1'],
    qualityHint: 8.4,
  },
  {
    id: 'hero-health-calm',
    category: 'hero',
    industry: ['health', 'wellness', 'mental-health', 'medical'],
    style: ['apple', 'notion'],
    layout: 'centered',
    tags: ['health', 'calm', 'green', 'wellness', 'soft'],
    description: 'Soft and calming health product hero, muted palette, empathetic headline, app download or consultation CTA.',
    componentIds: ['hero-health-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'hero-ai-product',
    category: 'hero',
    industry: ['ai', 'ml', 'saas', 'developer'],
    style: ['linear', 'cursor', 'framer'],
    layout: 'centered',
    tags: ['ai', 'neural', 'glow', 'streaming-text', 'animated'],
    description: 'AI product hero with animated streaming text output, glowing gradient accents, model capability badges.',
    componentIds: ['hero-ai-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'hero-open-source',
    category: 'hero',
    industry: ['developer', 'open-source', 'tooling'],
    style: ['vercel', 'linear'],
    layout: 'centered',
    tags: ['open-source', 'github-stars', 'cli', 'npm', 'community'],
    description: 'Developer-focused hero with GitHub star count, npm badge, quick install command in code block.',
    componentIds: ['hero-oss-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'hero-marketplace',
    category: 'hero',
    industry: ['marketplace', 'ecommerce', 'platform', 'saas'],
    style: ['stripe', 'notion'],
    layout: 'centered',
    tags: ['marketplace', 'search', 'categories', 'platform'],
    description: 'Marketplace hero with prominent search bar, category pills, trust metrics and featured listings.',
    componentIds: ['hero-marketplace-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'hero-geometric-art',
    category: 'hero',
    industry: ['creative', 'design', 'agency', 'art'],
    style: ['framer', 'raycast'],
    layout: 'centered',
    tags: ['geometric', 'art-direction', 'svg-pattern', 'creative'],
    description: 'Bold geometric SVG pattern or abstract art background, minimal dark overlay, large bold type.',
    componentIds: ['hero-geometric-v1'],
    qualityHint: 8.4,
  },
];

// ── FEATURES — 20 references ─────────────────────────────────────────────────
const featuresRefs: DesignReference[] = [
  {
    id: 'features-3col-grid',
    category: 'features',
    industry: ['saas', 'startup', 'productivity'],
    style: ['vercel', 'linear'],
    layout: '3-column-grid',
    tags: ['3-col', 'icon-card', 'grid', 'clean'],
    description: 'Classic 3-column icon + title + description card grid. Clean, scannable, works for 6–9 features.',
    componentIds: ['features-grid-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'features-bento-asymmetric',
    category: 'features',
    industry: ['saas', 'ai', 'developer', 'analytics'],
    style: ['framer', 'linear'],
    layout: 'bento',
    tags: ['bento', 'asymmetric', 'large-card', 'visual', 'animated'],
    description: 'Asymmetric bento grid with 1 large hero card and 4 smaller cards. Each card has a mini visual or animation.',
    componentIds: ['features-bento-v1'],
    qualityHint: 9.3,
  },
  {
    id: 'features-alternating',
    category: 'features',
    industry: ['saas', 'enterprise', 'fintech', 'health'],
    style: ['stripe', 'notion'],
    layout: 'alternating-split',
    tags: ['alternating', 'screenshot', 'left-right', 'step-by-step'],
    description: 'Alternating left/right split: screenshot or illustration left, text right, then flip. Good for complex features.',
    componentIds: ['features-alt-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'features-framer-animated',
    category: 'features',
    industry: ['saas', 'ai', 'startup', 'creative'],
    style: ['framer', 'raycast'],
    layout: 'staggered-grid',
    tags: ['animated', 'stagger', 'scroll-reveal', 'motion'],
    description: 'Feature cards with staggered scroll-reveal animations. Cards entrance from below with spring physics.',
    componentIds: ['features-framer-v1'],
    qualityHint: 9.4,
  },
  {
    id: 'features-timeline',
    category: 'features',
    industry: ['startup', 'agency', 'saas', 'developer'],
    style: ['linear', 'notion'],
    layout: 'vertical-timeline',
    tags: ['timeline', 'numbered', 'steps', 'how-it-works', 'vertical'],
    description: 'Vertical timeline or numbered steps layout showing product workflow or onboarding progression.',
    componentIds: ['features-timeline-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'features-icon-list',
    category: 'features',
    industry: ['saas', 'legal', 'health', 'enterprise'],
    style: ['notion', 'apple'],
    layout: 'two-column-list',
    tags: ['checkmarks', 'icon-list', '2-col', 'clean', 'professional'],
    description: '2-column checklist with icon + feature name. Simple and high-conversion for pricing/landing pages.',
    componentIds: ['features-list-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'features-tabbed',
    category: 'features',
    industry: ['saas', 'analytics', 'crm', 'enterprise'],
    style: ['linear', 'stripe'],
    layout: 'tabs',
    tags: ['tabs', 'interactive', 'product-tour', 'switching'],
    description: 'Tabbed feature section where each tab reveals a different product area with screenshot + copy.',
    componentIds: ['features-tabs-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'features-comparison',
    category: 'features',
    industry: ['saas', 'fintech', 'enterprise', 'startup'],
    style: ['stripe', 'vercel'],
    layout: 'comparison',
    tags: ['before-after', 'comparison', 'old-way', 'new-way'],
    description: 'Before/after or old-way/new-way split showing problem and solution side by side.',
    componentIds: ['features-compare-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'features-stats-bar',
    category: 'features',
    industry: ['enterprise', 'saas', 'fintech', 'analytics'],
    style: ['stripe', 'linear'],
    layout: 'stats-strip',
    tags: ['stats', 'numbers', 'metrics', 'social-proof-numbers'],
    description: 'Horizontal stats strip with large numbers and labels. Attention-grabbing proof of scale.',
    componentIds: ['features-stats-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'features-showcase',
    category: 'features',
    industry: ['saas', 'ai', 'developer', 'productivity'],
    style: ['linear', 'vercel'],
    layout: 'large-showcase',
    tags: ['large-visual', 'spotlight', 'single-feature', 'hero-feature'],
    description: 'Large visual showcase for a single marquee feature with annotation callouts and supporting copy.',
    componentIds: ['features-showcase-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'features-video-demo',
    category: 'features',
    industry: ['saas', 'consumer', 'productivity', 'ai'],
    style: ['apple', 'framer'],
    layout: 'video-centered',
    tags: ['video', 'demo', 'product-video', 'play-button'],
    description: 'Centered auto-play product demo video with ambient glow, brief headline and supporting text above.',
    componentIds: ['features-video-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'features-masonry',
    category: 'features',
    industry: ['creative', 'media', 'ecommerce', 'agency'],
    style: ['framer', 'raycast'],
    layout: 'masonry',
    tags: ['masonry', 'asymmetric', 'varied-size', 'editorial'],
    description: 'Masonry-style feature cards with varied heights for editorial visual rhythm.',
    componentIds: ['features-masonry-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'features-4col',
    category: 'features',
    industry: ['saas', 'ecommerce', 'marketplace', 'developer'],
    style: ['vercel', 'notion'],
    layout: '4-column-grid',
    tags: ['4-col', 'compact', 'many-features', 'icons'],
    description: '4-column compact grid for surfacing many features (8–12). Smaller cards with icon and brief label.',
    componentIds: ['features-4col-v1'],
    qualityHint: 8.3,
  },
  {
    id: 'features-accordion-detail',
    category: 'features',
    industry: ['enterprise', 'health', 'legal', 'saas'],
    style: ['notion', 'stripe'],
    layout: 'accordion',
    tags: ['accordion', 'expandable', 'detailed', 'long-copy'],
    description: 'Accordion-style feature list for complex products needing detailed explanations per feature.',
    componentIds: ['features-accordion-v1'],
    qualityHint: 8.4,
  },
  {
    id: 'features-table',
    category: 'features',
    industry: ['enterprise', 'saas', 'analytics', 'fintech'],
    style: ['linear', 'stripe'],
    layout: 'feature-table',
    tags: ['table', 'comparison-table', 'tier-features'],
    description: 'Feature availability table showing what is included across plans or product tiers.',
    componentIds: ['features-table-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'features-interactive-demo',
    category: 'features',
    industry: ['saas', 'developer', 'ai', 'productivity'],
    style: ['framer', 'linear'],
    layout: 'interactive',
    tags: ['interactive', 'live-demo', 'playground', 'try-now'],
    description: 'Interactive mini-product experience embedded in the features section — try before you buy.',
    componentIds: ['features-interactive-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'features-spotlight-carousel',
    category: 'features',
    industry: ['saas', 'ecommerce', 'consumer', 'ai'],
    style: ['apple', 'framer'],
    layout: 'carousel',
    tags: ['carousel', 'swiper', 'auto-rotate', 'spotlight'],
    description: 'Auto-rotating feature spotlight carousel with large visual and copy. Apple-style progressive reveal.',
    componentIds: ['features-carousel-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'features-numbered-steps',
    category: 'features',
    industry: ['saas', 'health', 'ecommerce', 'fintech'],
    style: ['stripe', 'notion'],
    layout: 'numbered',
    tags: ['numbered', 'step-by-step', 'how-it-works', 'process'],
    description: 'Large numbered step indicators (01, 02, 03...) with headline and description. How-it-works section.',
    componentIds: ['features-numbered-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'features-dark-cards',
    category: 'features',
    industry: ['ai', 'security', 'developer', 'saas'],
    style: ['linear', 'cursor'],
    layout: '3-column-grid',
    tags: ['dark', 'glow-border', 'card', 'premium'],
    description: 'Dark theme feature cards with subtle glow border on hover, icon with accent color, clean typography.',
    componentIds: ['features-dark-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'features-split-visual-static',
    category: 'features',
    industry: ['saas', 'health', 'education', 'enterprise'],
    style: ['apple', 'notion'],
    layout: 'split-layout',
    tags: ['split', 'large-visual', 'icon-list-right', 'light'],
    description: 'Large product visual left, icon+text feature list right. Clean and professional for enterprise.',
    componentIds: ['features-split-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'features-gradient-cards',
    category: 'features',
    industry: ['ai', 'startup', 'fintech', 'saas'],
    style: ['stripe', 'framer'],
    layout: '3-column-grid',
    tags: ['gradient-card', 'glass', 'colorful', 'modern'],
    description: 'Feature cards with subtle gradient backgrounds and glassmorphism. Modern colorful aesthetic.',
    componentIds: ['features-gradient-v1'],
    qualityHint: 8.8,
  },
];

// ── PRICING — 15 references ───────────────────────────────────────────────────
const pricingRefs: DesignReference[] = [
  {
    id: 'pricing-3tier',
    category: 'pricing',
    industry: ['saas', 'startup', 'enterprise', 'developer'],
    style: ['stripe', 'linear'],
    layout: '3-column',
    tags: ['3-tier', 'monthly-annual-toggle', 'popular-badge', 'feature-list'],
    description: 'Classic 3-tier pricing: Starter / Pro / Enterprise with monthly/annual toggle and popular badge.',
    componentIds: ['pricing-3tier-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'pricing-2tier',
    category: 'pricing',
    industry: ['startup', 'saas', 'consumer', 'freelance'],
    style: ['notion', 'vercel'],
    layout: '2-column',
    tags: ['2-tier', 'simple', 'free-paid', 'clean'],
    description: 'Simple two-tier pricing: Free and Pro. Clean, minimal, high-conversion.',
    componentIds: ['pricing-2tier-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'pricing-freemium',
    category: 'pricing',
    industry: ['consumer', 'saas', 'social', 'developer'],
    style: ['linear', 'vercel'],
    layout: 'freemium',
    tags: ['freemium', 'free-forever', 'upgrade-path'],
    description: 'Freemium model: Free-forever card + Pro upgrade. Limit rows showing what unlocks at Pro.',
    componentIds: ['pricing-freemium-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'pricing-enterprise-focus',
    category: 'pricing',
    industry: ['enterprise', 'b2b', 'security', 'analytics'],
    style: ['stripe', 'notion'],
    layout: 'enterprise-cta',
    tags: ['enterprise', 'contact-sales', 'custom-pricing', 'sla'],
    description: 'Standard plans + prominent enterprise card with custom pricing, SLA, and "contact sales" CTA.',
    componentIds: ['pricing-enterprise-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'pricing-usage-based',
    category: 'pricing',
    industry: ['developer', 'api', 'ai', 'saas'],
    style: ['linear', 'vercel'],
    layout: 'usage-calculator',
    tags: ['usage-based', 'pay-as-you-go', 'calculator', 'slider'],
    description: 'Usage-based pricing with interactive slider to estimate monthly cost. Shows $0 to enterprise tier.',
    componentIds: ['pricing-usage-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'pricing-dark-gradient',
    category: 'pricing',
    industry: ['ai', 'saas', 'developer', 'fintech'],
    style: ['framer', 'cursor'],
    layout: '3-column',
    tags: ['dark', 'gradient', 'glow', 'premium'],
    description: 'Dark premium pricing cards with gradient borders and hover glow effects.',
    componentIds: ['pricing-dark-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'pricing-feature-comparison-table',
    category: 'pricing',
    industry: ['enterprise', 'saas', 'b2b', 'analytics'],
    style: ['stripe', 'notion'],
    layout: 'comparison-table',
    tags: ['feature-table', 'comparison', 'checkmarks', 'detailed'],
    description: 'Full feature-comparison table below tier cards. Check/cross per feature, grouped by category.',
    componentIds: ['pricing-table-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'pricing-toggle-annual',
    category: 'pricing',
    industry: ['saas', 'startup', 'enterprise'],
    style: ['linear', 'stripe'],
    layout: '3-column',
    tags: ['toggle', 'annual-savings', 'save-badge', 'conversion'],
    description: 'Toggle switch for monthly/annual with "save 20%" badge animating on selection change.',
    componentIds: ['pricing-toggle-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'pricing-card-minimal',
    category: 'pricing',
    industry: ['freelance', 'agency', 'consulting', 'startup'],
    style: ['notion', 'apple'],
    layout: 'centered-card',
    tags: ['minimal', 'single-plan', 'flat-rate', 'simple'],
    description: 'Single pricing card centered on screen. Flat-rate with all features listed. Simple and high-trust.',
    componentIds: ['pricing-minimal-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'pricing-seats-team',
    category: 'pricing',
    industry: ['saas', 'productivity', 'collaboration', 'enterprise'],
    style: ['linear', 'stripe'],
    layout: '3-column',
    tags: ['per-seat', 'team', 'collaboration', 'seats'],
    description: 'Per-seat team pricing: Individual / Team / Organization. Seat count selector on each card.',
    componentIds: ['pricing-seats-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'pricing-lifetime-deal',
    category: 'pricing',
    industry: ['saas', 'consumer', 'startup'],
    style: ['framer', 'raycast'],
    layout: 'split',
    tags: ['lifetime', 'one-time', 'deal', 'strikethrough'],
    description: 'Lifetime deal card alongside subscription. Shows original price struck through with deal price.',
    componentIds: ['pricing-lifetime-v1'],
    qualityHint: 8.4,
  },
  {
    id: 'pricing-api-credits',
    category: 'pricing',
    industry: ['ai', 'developer', 'api'],
    style: ['cursor', 'linear'],
    layout: 'credits-grid',
    tags: ['credits', 'tokens', 'api-calls', 'developer'],
    description: 'Credit-bundle pricing for AI/API products. Shows requests/tokens per price point with rollover info.',
    componentIds: ['pricing-credits-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'pricing-horizontal-cards',
    category: 'pricing',
    industry: ['saas', 'startup', 'health'],
    style: ['apple', 'notion'],
    layout: 'horizontal-list',
    tags: ['horizontal', 'scrollable', 'mobile-first'],
    description: 'Horizontally scrollable pricing cards. Works great on mobile-first products.',
    componentIds: ['pricing-horizontal-v1'],
    qualityHint: 8.3,
  },
  {
    id: 'pricing-open-source',
    category: 'pricing',
    industry: ['developer', 'open-source', 'saas'],
    style: ['vercel', 'linear'],
    layout: 'oss-tiers',
    tags: ['open-source', 'self-host', 'cloud', 'community'],
    description: 'Self-hosted (free) + Cloud (paid) + Enterprise. Designed for open-source to commercial products.',
    componentIds: ['pricing-oss-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'pricing-edu-nonprofit',
    category: 'pricing',
    industry: ['edtech', 'nonprofit', 'education'],
    style: ['notion', 'apple'],
    layout: 'special-tiers',
    tags: ['edu-discount', 'nonprofit', 'student', 'discount'],
    description: 'Standard pricing with EDU/nonprofit discount banner or separate card at reduced rate.',
    componentIds: ['pricing-edu-v1'],
    qualityHint: 8.2,
  },
];

// ── TESTIMONIALS — 10 references ──────────────────────────────────────────────
const testimonialsRefs: DesignReference[] = [
  {
    id: 'testimonials-wall',
    category: 'testimonials',
    industry: ['saas', 'enterprise', 'startup', 'consumer'],
    style: ['framer', 'linear'],
    layout: 'masonry-wall',
    tags: ['wall', 'masonry', 'many-reviews', 'social-wall'],
    description: 'Masonry wall of testimonial cards with varied heights. High-volume social proof display.',
    componentIds: ['testimonials-wall-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'testimonials-marquee',
    category: 'testimonials',
    industry: ['saas', 'ecommerce', 'startup', 'ai'],
    style: ['linear', 'framer'],
    layout: 'marquee',
    tags: ['marquee', 'scrolling', 'infinite', 'auto-scroll'],
    description: 'Infinite horizontal marquee of testimonial cards. Continuous scrolling motion creates energy.',
    componentIds: ['testimonials-marquee-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'testimonials-large-single',
    category: 'testimonials',
    industry: ['enterprise', 'fintech', 'health', 'consulting'],
    style: ['stripe', 'notion'],
    layout: 'single-spotlight',
    tags: ['single', 'quote', 'large-text', 'authority'],
    description: 'Single large testimonial quote with photo, name, role, and company logo. High trust authority signal.',
    componentIds: ['testimonials-single-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'testimonials-slider',
    category: 'testimonials',
    industry: ['saas', 'health', 'edtech', 'consumer'],
    style: ['apple', 'notion'],
    layout: 'slider',
    tags: ['slider', 'arrows', 'dots', 'swipeable'],
    description: 'Testimonial carousel with arrow navigation and dot indicators. Shows 3 at a time on desktop.',
    componentIds: ['testimonials-slider-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'testimonials-logo-plus-quote',
    category: 'testimonials',
    industry: ['enterprise', 'b2b', 'saas', 'agency'],
    style: ['stripe', 'linear'],
    layout: 'logo-grid-plus-featured',
    tags: ['logo-cloud', 'featured-quote', 'combined', 'enterprise'],
    description: 'Logo cloud of customer logos plus 1–2 featured case-study quotes below. Enterprise trust builder.',
    componentIds: ['testimonials-logos-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'testimonials-video',
    category: 'testimonials',
    industry: ['saas', 'health', 'edtech', 'consumer'],
    style: ['apple', 'framer'],
    layout: 'video-grid',
    tags: ['video', 'loom', 'video-testimonial', 'face'],
    description: 'Grid of video testimonial thumbnails with play button. Face-to-face credibility.',
    componentIds: ['testimonials-video-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'testimonials-twitter-wall',
    category: 'testimonials',
    industry: ['consumer', 'saas', 'startup', 'ai'],
    style: ['framer', 'linear'],
    layout: 'twitter-grid',
    tags: ['twitter', 'x', 'social-media', 'embedded', 'screenshot'],
    description: 'Grid of Twitter/X screenshot cards with like counts. Authentic social proof from real users.',
    componentIds: ['testimonials-twitter-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'testimonials-case-study',
    category: 'testimonials',
    industry: ['enterprise', 'saas', 'b2b', 'consulting'],
    style: ['stripe', 'notion'],
    layout: 'case-study-cards',
    tags: ['case-study', 'results', 'roi', 'before-after'],
    description: 'Case study cards: company name, challenge, solution, result (% improvement). Detailed social proof.',
    componentIds: ['testimonials-case-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'testimonials-avatar-row',
    category: 'testimonials',
    industry: ['saas', 'startup', 'consumer', 'health'],
    style: ['notion', 'apple'],
    layout: '3-column-cards',
    tags: ['avatar', 'stars', '3-col', 'simple', 'friendly'],
    description: '3-column testimonial cards with avatar photo, star rating, name, and short quote.',
    componentIds: ['testimonials-avatars-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'testimonials-number-stats',
    category: 'testimonials',
    industry: ['enterprise', 'fintech', 'analytics', 'saas'],
    style: ['stripe', 'linear'],
    layout: 'stats-plus-quotes',
    tags: ['stats', 'numbers', 'roi-stats', 'combined'],
    description: 'Large stats strip (NPS, satisfaction %, customers) followed by 3 supporting quotes.',
    componentIds: ['testimonials-stats-v1'],
    qualityHint: 8.8,
  },
];

// ── DASHBOARD — 10 references ─────────────────────────────────────────────────
const dashboardRefs: DesignReference[] = [
  {
    id: 'dashboard-analytics',
    category: 'dashboard',
    industry: ['analytics', 'saas', 'marketing', 'ecommerce'],
    style: ['linear', 'vercel'],
    layout: 'sidebar-main',
    tags: ['charts', 'kpi', 'line-chart', 'analytics', 'dark'],
    description: 'Dark analytics dashboard with sidebar nav, KPI cards row, line/bar charts, and data table.',
    componentIds: ['dashboard-analytics-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'dashboard-crm',
    category: 'dashboard',
    industry: ['crm', 'sales', 'enterprise', 'b2b'],
    style: ['stripe', 'notion'],
    layout: 'sidebar-main',
    tags: ['crm', 'pipeline', 'contacts', 'deals', 'funnel'],
    description: 'CRM dashboard with sales pipeline stages, contact list, and deal status indicators.',
    componentIds: ['dashboard-crm-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'dashboard-finance',
    category: 'dashboard',
    industry: ['fintech', 'banking', 'payments', 'crypto'],
    style: ['linear', 'cursor'],
    layout: 'card-grid',
    tags: ['balance', 'transactions', 'spending', 'finance', 'dark'],
    description: 'Finance dashboard with account balance, recent transactions, spending breakdown charts.',
    componentIds: ['dashboard-finance-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'dashboard-project',
    category: 'dashboard',
    industry: ['productivity', 'saas', 'agency', 'developer'],
    style: ['linear', 'notion'],
    layout: 'kanban',
    tags: ['kanban', 'tasks', 'project', 'board', 'collaboration'],
    description: 'Project management dashboard with kanban columns, task cards, progress tracking.',
    componentIds: ['dashboard-project-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'dashboard-health',
    category: 'dashboard',
    industry: ['health', 'wellness', 'medical', 'fitness'],
    style: ['apple', 'notion'],
    layout: 'card-grid',
    tags: ['vitals', 'health-metrics', 'heart-rate', 'steps', 'clean'],
    description: 'Health metrics dashboard with activity rings, vitals cards, and trend sparklines. Light and calming.',
    componentIds: ['dashboard-health-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'dashboard-ecommerce',
    category: 'dashboard',
    industry: ['ecommerce', 'retail', 'marketplace'],
    style: ['stripe', 'linear'],
    layout: 'sidebar-main',
    tags: ['orders', 'revenue', 'inventory', 'sales', 'products'],
    description: 'Ecommerce admin dashboard: revenue chart, recent orders table, product inventory, conversion metrics.',
    componentIds: ['dashboard-ecom-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'dashboard-monitoring',
    category: 'dashboard',
    industry: ['developer', 'devops', 'security', 'saas'],
    style: ['linear', 'cursor'],
    layout: 'grid',
    tags: ['uptime', 'monitoring', 'errors', 'latency', 'dark'],
    description: 'Site/API monitoring dashboard: uptime status, p95 latency chart, error rate, incident history.',
    componentIds: ['dashboard-monitor-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'dashboard-social',
    category: 'dashboard',
    industry: ['social', 'media', 'marketing', 'creator'],
    style: ['framer', 'linear'],
    layout: 'card-grid',
    tags: ['followers', 'engagement', 'posts', 'reach', 'analytics'],
    description: 'Social media analytics dashboard: follower growth, engagement rate, post performance grid.',
    componentIds: ['dashboard-social-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'dashboard-admin-light',
    category: 'dashboard',
    industry: ['saas', 'enterprise', 'productivity'],
    style: ['notion', 'apple'],
    layout: 'sidebar-main',
    tags: ['admin', 'light', 'clean', 'settings', 'users'],
    description: 'Light-theme admin panel with user management table, settings sidebar, activity log.',
    componentIds: ['dashboard-admin-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'dashboard-ai-metrics',
    category: 'dashboard',
    industry: ['ai', 'ml', 'developer', 'saas'],
    style: ['cursor', 'linear'],
    layout: 'grid',
    tags: ['tokens', 'requests', 'models', 'latency', 'ai'],
    description: 'AI model usage dashboard: token usage chart, request volume, model selection stats, cost tracker.',
    componentIds: ['dashboard-ai-v1'],
    qualityHint: 9.1,
  },
];

// ── FAQ — 8 references ────────────────────────────────────────────────────────
const faqRefs: DesignReference[] = [
  {
    id: 'faq-accordion',
    category: 'faq',
    industry: ['saas', 'startup', 'ecommerce', 'health'],
    style: ['linear', 'notion'],
    layout: 'accordion',
    tags: ['accordion', 'expand-collapse', 'clean', 'standard'],
    description: 'Standard accordion FAQ. Single column, each question expands to reveal answer.',
    componentIds: ['faq-accordion-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'faq-2col',
    category: 'faq',
    industry: ['saas', 'enterprise', 'ecommerce'],
    style: ['stripe', 'vercel'],
    layout: '2-column-accordion',
    tags: ['2-col', 'accordion', 'space-efficient', 'compact'],
    description: '2-column accordion FAQ for pages with many questions (8+). More space-efficient layout.',
    componentIds: ['faq-2col-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'faq-search',
    category: 'faq',
    industry: ['saas', 'enterprise', 'marketplace', 'developer'],
    style: ['linear', 'notion'],
    layout: 'searchable',
    tags: ['search', 'filter', 'large-faq', 'interactive'],
    description: 'Searchable FAQ with category filter tabs. Ideal for products with 20+ FAQ items.',
    componentIds: ['faq-search-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'faq-minimal',
    category: 'faq',
    industry: ['startup', 'freelance', 'agency', 'consumer'],
    style: ['notion', 'apple'],
    layout: 'flat-list',
    tags: ['minimal', 'borderless', 'clean', 'simple'],
    description: 'Minimal flat FAQ list without border/accordion chrome. Just Q+A in clean typography.',
    componentIds: ['faq-minimal-v1'],
    qualityHint: 8.5,
  },
  {
    id: 'faq-split-contact',
    category: 'faq',
    industry: ['saas', 'enterprise', 'health', 'legal'],
    style: ['stripe', 'notion'],
    layout: 'split-with-contact',
    tags: ['split', 'contact-form', 'support', 'left-faq', 'right-contact'],
    description: 'Left side FAQ accordion, right side contact/support form. Handles support questions directly.',
    componentIds: ['faq-split-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'faq-categorized',
    category: 'faq',
    industry: ['enterprise', 'saas', 'ecommerce', 'marketplace'],
    style: ['stripe', 'linear'],
    layout: 'tabbed-categories',
    tags: ['categories', 'tabs', 'grouped', 'organized'],
    description: 'FAQ grouped by category with tab navigation: Billing, Features, Security, Account, etc.',
    componentIds: ['faq-categories-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'faq-grid-cards',
    category: 'faq',
    industry: ['startup', 'saas', 'developer', 'ai'],
    style: ['framer', 'raycast'],
    layout: 'card-grid',
    tags: ['cards', 'grid', 'visual', 'modern'],
    description: 'FAQ as card grid with icon per topic. Clicking card expands inline answer below.',
    componentIds: ['faq-grid-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'faq-inline-cta',
    category: 'faq',
    industry: ['saas', 'ecommerce', 'health', 'consumer'],
    style: ['stripe', 'apple'],
    layout: 'accordion-with-cta',
    tags: ['cta-footer', 'still-questions', 'support-link'],
    description: 'Standard accordion FAQ ending with a "Still have questions?" CTA linking to support.',
    componentIds: ['faq-cta-v1'],
    qualityHint: 8.8,
  },
];

// ── CTA — 8 references ────────────────────────────────────────────────────────
const ctaRefs: DesignReference[] = [
  {
    id: 'cta-full-width-dark',
    category: 'cta',
    industry: ['saas', 'startup', 'developer', 'enterprise'],
    style: ['linear', 'vercel'],
    layout: 'full-width',
    tags: ['full-width', 'dark-band', 'centered', 'final-cta'],
    description: 'Full-width dark band CTA section. Centered headline + subtext + primary CTA. Classic page ending.',
    componentIds: ['cta-dark-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'cta-gradient-band',
    category: 'cta',
    industry: ['fintech', 'saas', 'ai', 'startup'],
    style: ['stripe', 'framer'],
    layout: 'gradient-full-width',
    tags: ['gradient', 'colorful', 'bold', 'high-contrast'],
    description: 'Full-width gradient CTA band. Bold, high-energy, works for launch or conversion push.',
    componentIds: ['cta-gradient-v1'],
    qualityHint: 9.1,
  },
  {
    id: 'cta-split',
    category: 'cta',
    industry: ['saas', 'health', 'edtech', 'enterprise'],
    style: ['notion', 'stripe'],
    layout: 'split',
    tags: ['split', '2-cta', 'primary-secondary', 'choice'],
    description: 'Split CTA with two options: start free (primary) and book demo (secondary) side by side.',
    componentIds: ['cta-split-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'cta-newsletter',
    category: 'cta',
    industry: ['media', 'creator', 'startup', 'consumer'],
    style: ['notion', 'apple'],
    layout: 'email-capture',
    tags: ['newsletter', 'email', 'subscribe', 'input'],
    description: 'Email newsletter subscription CTA with input field + subscribe button inline.',
    componentIds: ['cta-newsletter-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'cta-free-trial',
    category: 'cta',
    industry: ['saas', 'developer', 'enterprise', 'productivity'],
    style: ['linear', 'stripe'],
    layout: 'centered-card',
    tags: ['free-trial', 'no-credit-card', 'days', 'risk-free'],
    description: 'Trial CTA card: "Start free 14-day trial, no credit card required" with supporting trust signals.',
    componentIds: ['cta-trial-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'cta-book-demo',
    category: 'cta',
    industry: ['enterprise', 'b2b', 'fintech', 'health'],
    style: ['stripe', 'notion'],
    layout: 'centered',
    tags: ['demo', 'schedule', 'calendar', 'sales'],
    description: 'Book a demo CTA with Calendly-style or form integration. Key for B2B sales funnels.',
    componentIds: ['cta-demo-v1'],
    qualityHint: 8.9,
  },
  {
    id: 'cta-minimal-clean',
    category: 'cta',
    industry: ['startup', 'agency', 'creative', 'freelance'],
    style: ['apple', 'notion'],
    layout: 'minimal',
    tags: ['minimal', 'clean', 'simple-headline', 'single-button'],
    description: 'Minimal CTA: one line headline, one button. Extreme clarity and whitespace.',
    componentIds: ['cta-minimal-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'cta-waitlist',
    category: 'cta',
    industry: ['startup', 'consumer', 'ai', 'saas'],
    style: ['framer', 'raycast'],
    layout: 'waitlist',
    tags: ['waitlist', 'early-access', 'launch', 'email-capture'],
    description: 'Waitlist signup CTA for pre-launch. Shows position count, expected launch date.',
    componentIds: ['cta-waitlist-v1'],
    qualityHint: 8.8,
  },
];

// ── NAVBAR — 8 references ─────────────────────────────────────────────────────
const navbarRefs: DesignReference[] = [
  {
    id: 'navbar-minimal-dark',
    category: 'navbar',
    industry: ['saas', 'startup', 'developer', 'ai'],
    style: ['linear', 'vercel'],
    layout: 'horizontal-minimal',
    tags: ['minimal', 'dark', 'logo-left', 'links-center', 'cta-right'],
    description: 'Dark minimal navbar: logo left, nav links center, login + CTA button right.',
    componentIds: ['navbar-minimal-v1'],
    qualityHint: 9.2,
  },
  {
    id: 'navbar-glass-sticky',
    category: 'navbar',
    industry: ['saas', 'startup', 'agency', 'creative'],
    style: ['framer', 'cursor'],
    layout: 'sticky-glass',
    tags: ['glass', 'sticky', 'backdrop-blur', 'scroll'],
    description: 'Sticky navbar with glassmorphism blur on scroll. Transparent at top, frosted glass when scrolled.',
    componentIds: ['navbar-glass-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'navbar-mega-menu',
    category: 'navbar',
    industry: ['enterprise', 'saas', 'marketplace', 'b2b'],
    style: ['stripe', 'notion'],
    layout: 'mega-menu',
    tags: ['mega-menu', 'dropdown', 'complex-nav', 'enterprise'],
    description: 'Enterprise navbar with multi-column mega dropdown menus for Products, Solutions, Resources.',
    componentIds: ['navbar-mega-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'navbar-light-clean',
    category: 'navbar',
    industry: ['health', 'legal', 'finance', 'education'],
    style: ['notion', 'apple'],
    layout: 'horizontal-light',
    tags: ['light', 'clean', 'professional', 'border-bottom'],
    description: 'Light background navbar with subtle bottom border. Professional and accessible.',
    componentIds: ['navbar-light-v1'],
    qualityHint: 8.7,
  },
  {
    id: 'navbar-mobile-first',
    category: 'navbar',
    industry: ['consumer', 'ecommerce', 'health', 'social'],
    style: ['apple', 'framer'],
    layout: 'mobile-hamburger',
    tags: ['mobile', 'hamburger', 'drawer', 'responsive'],
    description: 'Mobile-first navbar with hamburger menu opening a full-height drawer on mobile.',
    componentIds: ['navbar-mobile-v1'],
    qualityHint: 8.6,
  },
  {
    id: 'navbar-announcement',
    category: 'navbar',
    industry: ['saas', 'ecommerce', 'startup'],
    style: ['linear', 'stripe'],
    layout: 'with-banner',
    tags: ['announcement-bar', 'banner', 'promotion', 'above-nav'],
    description: 'Slim announcement bar above main navbar. Dismissable. Good for product launches or promotions.',
    componentIds: ['navbar-announce-v1'],
    qualityHint: 8.8,
  },
  {
    id: 'navbar-fixed-app',
    category: 'navbar',
    industry: ['dashboard', 'saas', 'productivity', 'developer'],
    style: ['linear', 'vercel'],
    layout: 'fixed-app-header',
    tags: ['app', 'fixed', 'user-avatar', 'search', 'notifications'],
    description: 'App-style fixed header with search bar, notification bell, and user avatar menu.',
    componentIds: ['navbar-app-v1'],
    qualityHint: 9.0,
  },
  {
    id: 'navbar-centered-logo',
    category: 'navbar',
    industry: ['ecommerce', 'fashion', 'agency', 'creative'],
    style: ['apple', 'notion'],
    layout: 'centered-logo',
    tags: ['centered-logo', 'editorial', 'fashion', 'magazine'],
    description: 'Centered logo with navigation links split evenly on both sides. Editorial/fashion aesthetic.',
    componentIds: ['navbar-centered-v1'],
    qualityHint: 8.5,
  },
];

// ── Full Corpus ───────────────────────────────────────────────────────────────
export const DESIGN_CORPUS: DesignReference[] = [
  ...heroRefs,
  ...featuresRefs,
  ...pricingRefs,
  ...testimonialsRefs,
  ...dashboardRefs,
  ...faqRefs,
  ...ctaRefs,
  ...navbarRefs,
];

// Quick accessors
export function getByCategory(category: DesignCategory): DesignReference[] {
  return DESIGN_CORPUS.filter(r => r.category === category);
}

export function getById(id: string): DesignReference | undefined {
  return DESIGN_CORPUS.find(r => r.id === id);
}

export function getCategoryCount(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const ref of DESIGN_CORPUS) {
    counts[ref.category] = (counts[ref.category] ?? 0) + 1;
  }
  return counts;
}

export function getStyleCount(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const ref of DESIGN_CORPUS) {
    for (const s of ref.style) {
      counts[s] = (counts[s] ?? 0) + 1;
    }
  }
  return counts;
}
