// ── V7.2.9 Motion Intelligence Engine — Motion RAG Corpus ────────────────────
// 156 motion references across 8 categories × 8 DNA profiles.

export type MotionCategory =
  | 'hero-motion' | 'features-motion' | 'pricing-motion'
  | 'testimonials-motion' | 'faq-motion' | 'dashboard-motion'
  | 'cta-motion' | 'navbar-motion';

export type MotionDNA =
  | 'linear' | 'stripe' | 'vercel' | 'framer' | 'apple'
  | 'notion' | 'cursor' | 'raycast';

export type AnimationType =
  | 'fade' | 'fadeUp' | 'fadeDown' | 'slideLeft' | 'slideRight'
  | 'scaleIn' | 'stagger' | 'none';

export type MotionIntensity = 'low' | 'medium' | 'high';

export interface MotionReference {
  id: string;
  category: MotionCategory;
  dna: MotionDNA[];
  animationType: AnimationType[];
  duration: number;    // ms
  delay: number;       // ms base delay
  stagger: number;     // ms between staggered children (0 = no stagger)
  intensity: MotionIntensity;
  qualityHint: number; // 0–10 baseline quality estimate
  description: string;
  codeHint: string;    // key framer-motion pattern to use
}

// ── HERO MOTION — 20 references ───────────────────────────────────────────────
const heroMotionRefs: MotionReference[] = [
  {
    id: 'hero-motion-linear-fade-up',
    category: 'hero-motion', dna: ['linear', 'vercel'],
    animationType: ['fadeUp', 'stagger'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.2,
    description: 'Linear-style: badge fades up first, H1 staggered 80ms after, subtext follows. Pure opacity + translateY(16px→0). No scale.',
    codeHint: 'variants={{ hidden:{opacity:0,y:16}, visible:{opacity:1,y:0} }} transition={{ duration:0.25 }} staggerChildren:0.08',
  },
  {
    id: 'hero-motion-vercel-opacity',
    category: 'hero-motion', dna: ['vercel', 'notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel-style: pure opacity fade, no translate. Children stagger 60ms. Minimalist — motion barely visible.',
    codeHint: 'variants={{ hidden:{opacity:0}, visible:{opacity:1} }} transition={{ duration:0.2, ease:"easeOut" }}',
  },
  {
    id: 'hero-motion-stripe-stagger',
    category: 'hero-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 100, stagger: 100,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Stripe-style: hero container enters with staggered children. Badge → H1 → subtext → CTA row → trust strip. Each 100ms apart.',
    codeHint: 'container variants staggerChildren:0.1, delayChildren:0.1; children fadeUp y:20→0 duration:0.3',
  },
  {
    id: 'hero-motion-framer-scale-stagger',
    category: 'hero-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 350, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer-style: headline scales from 0.92 to 1.0 with fadeUp. CTA buttons scale in with spring. Rich, expressive entrance.',
    codeHint: 'variants={{ hidden:{opacity:0,scale:0.92,y:20}, visible:{opacity:1,scale:1,y:0} }} transition={{ type:"spring", stiffness:200, damping:20 }}',
  },
  {
    id: 'hero-motion-apple-smooth',
    category: 'hero-motion', dna: ['apple'],
    animationType: ['fadeUp', 'scaleIn'], duration: 350, delay: 50, stagger: 90,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Apple-style: smooth scale 0.96→1.0 with fade. Elegant timing curve. No bounce, no jitter. Feels premium and deliberate.',
    codeHint: 'variants={{ hidden:{opacity:0,scale:0.96,y:12}, visible:{opacity:1,scale:1,y:0} }} transition={{ duration:0.35, ease:[0.25,0.46,0.45,0.94] }}',
  },
  {
    id: 'hero-motion-cursor-slide',
    category: 'hero-motion', dna: ['cursor', 'linear'],
    animationType: ['slideLeft', 'fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor/dev-minimal: content slides in from x:-8 with opacity. Fast, sharp, no overshoot. Terminal-inspired precision.',
    codeHint: 'variants={{ hidden:{opacity:0,x:-8}, visible:{opacity:1,x:0} }} transition={{ duration:0.2, ease:"easeOut" }}',
  },
  {
    id: 'hero-motion-notion-static',
    category: 'hero-motion', dna: ['notion'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 40,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion-style: almost imperceptible fade-in. Very fast 150ms. No translate, no scale. Editorial calm.',
    codeHint: 'variants={{ hidden:{opacity:0}, visible:{opacity:1} }} transition={{ duration:0.15 }}',
  },
  {
    id: 'hero-motion-raycast-up',
    category: 'hero-motion', dna: ['raycast', 'cursor'],
    animationType: ['fadeUp', 'stagger'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.1,
    description: 'Raycast-style: smooth fadeUp y:8→0. Fast stagger. Developer-focused restraint with micro-movement.',
    codeHint: 'staggerChildren:0.07; each child y:8→0, opacity:0→1, duration:0.25',
  },
  {
    id: 'hero-motion-framer-spring-badge',
    category: 'hero-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeUp'], duration: 400, delay: 0, stagger: 150,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer-style: badge bounces in with spring at scale 0→1. H1 then rises. CTA row slides up last. Dramatic entrance.',
    codeHint: 'badge: type:"spring" stiffness:400 damping:25; h1: duration:0.4 y:24→0; cta: delay:0.3',
  },
  {
    id: 'hero-motion-stripe-reveal',
    category: 'hero-motion', dna: ['stripe', 'apple'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 300, delay: 80, stagger: 110,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Stripe/Apple cross: hero content reveals with stagger. Scale 0.97→1 subtle. Trust strip slides up last at 350ms delay.',
    codeHint: 'container staggerChildren:0.11 delayChildren:0.08; scale:0.97→1 opacity:0→1 duration:0.3',
  },
  {
    id: 'hero-motion-linear-badge-slide',
    category: 'hero-motion', dna: ['linear'],
    animationType: ['slideLeft', 'fade'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear-style: badge slides from x:-4 with fade. H1 and body use fadeUp. CTA buttons fade last.',
    codeHint: 'badge: x:-4→0 opacity:0→1; rest: y:12→0 opacity:0→1; staggerChildren:0.08',
  },
  {
    id: 'hero-motion-vercel-split',
    category: 'hero-motion', dna: ['vercel'],
    animationType: ['slideLeft', 'slideRight', 'fade'], duration: 300, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.1,
    description: 'Vercel split-layout: left text slides from x:-12, right visual slides from x:12. Both fade simultaneously. No stagger.',
    codeHint: 'leftCol: x:-12→0 opacity:0→1; rightCol: x:12→0 opacity:0→1; both duration:0.3',
  },
  {
    id: 'hero-motion-apple-hero-words',
    category: 'hero-motion', dna: ['apple', 'framer'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 40,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Apple word-by-word entrance on H1. Each word or span fades up independently with 40ms gap. Premium editorial feel.',
    codeHint: 'split H1 into spans; staggerChildren:0.04; each: y:8→0 opacity:0→1 duration:0.3',
  },
  {
    id: 'hero-motion-reduced-fallback',
    category: 'hero-motion', dna: ['linear', 'vercel', 'stripe', 'framer', 'apple', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced-motion fallback: useReducedMotion() → opacity only, no translate, no scale, no stagger. Always include.',
    codeHint: 'const reduced = useReducedMotion(); variants: reduced ? {hidden:{opacity:0},visible:{opacity:1}} : fullVariants',
  },
  {
    id: 'hero-motion-cursor-fast',
    category: 'hero-motion', dna: ['cursor'],
    animationType: ['fade', 'fadeUp'], duration: 150, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor style: ultra-fast 150ms fade with minimal y:6 translate. Instant-feeling entrance. Clean and terminal-sharp.',
    codeHint: 'y:6→0 opacity:0→1 duration:0.15; staggerChildren:0.05',
  },
  {
    id: 'hero-motion-stripe-gradient-sweep',
    category: 'hero-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 350, delay: 0, stagger: 120,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe with gradient text reveal: H1 gradient-text fades in while scaling 0.95→1. Paired with staggered badge + CTA.',
    codeHint: 'h1: scale:0.95→1 opacity:0→1 duration:0.35; badge delayChildren:0 then h1 delay:0.1 then cta delay:0.25',
  },
  {
    id: 'hero-motion-notion-editorial',
    category: 'hero-motion', dna: ['notion'],
    animationType: ['fadeDown'], duration: 200, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion editorial: content fades down from y:-8 (not up). Suits editorial top-heavy layouts. Very subtle.',
    codeHint: 'y:-8→0 opacity:0→1 duration:0.2; staggerChildren:0.05',
  },
  {
    id: 'hero-motion-framer-hero-entrance',
    category: 'hero-motion', dna: ['framer'],
    animationType: ['scaleIn', 'stagger', 'fadeUp'], duration: 400, delay: 100, stagger: 130,
    intensity: 'high', qualityHint: 9.8,
    description: 'Full Framer entrance: AnimatePresence wraps hero. Container springs in. Children stagger with spring physics. CTA pulses on initial render.',
    codeHint: 'AnimatePresence; container spring stiffness:180 damping:22; staggerChildren:0.13 delayChildren:0.1',
  },
  {
    id: 'hero-motion-raycast-fast-stagger',
    category: 'hero-motion', dna: ['raycast'],
    animationType: ['fadeUp', 'stagger'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Raycast hero: fast stagger on all headline elements. Developer-grade precision. Pairs with monospace badge.',
    codeHint: 'staggerChildren:0.06; y:10→0 opacity:0→1 duration:0.2 each child',
  },
  {
    id: 'hero-motion-apple-cta-hover',
    category: 'hero-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fade'], duration: 250, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple CTA interaction: whileHover scale:1.02 on primary button. whileTap scale:0.98. Micro-interaction on all CTAs.',
    codeHint: 'whileHover={{ scale:1.02 }} whileTap={{ scale:0.98 }} transition={{ type:"spring", stiffness:400, damping:25 }}',
  },
];

// ── FEATURES MOTION — 20 references ───────────────────────────────────────────
const featuresMotionRefs: MotionReference[] = [
  {
    id: 'features-motion-stagger-cards',
    category: 'features-motion', dna: ['stripe', 'framer', 'apple'],
    animationType: ['stagger', 'fadeUp'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Feature cards stagger in from below using whileInView. Each card fades up with 100ms gap. useInView threshold 0.1.',
    codeHint: 'container staggerChildren:0.1; card: y:24→0 opacity:0→1; viewport={{ once:true, margin:"-50px" }}',
  },
  {
    id: 'features-motion-linear-subtle',
    category: 'features-motion', dna: ['linear', 'vercel'],
    animationType: ['fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.2,
    description: 'Linear-style feature list: each item fades up with y:12. Very subtle. No scale. Minimal footprint.',
    codeHint: 'whileInView y:12→0 opacity:0→1 duration:0.25; viewport once:true; stagger 0.08',
  },
  {
    id: 'features-motion-framer-icon-spring',
    category: 'features-motion', dna: ['framer'],
    animationType: ['scaleIn', 'stagger'], duration: 350, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer feature icons spring in at scale:0→1. Cards follow with stagger. whileHover scale:1.03 on card.',
    codeHint: 'icon: scale:0→1 spring stiffness:300 damping:20; card hover: scale:1.03; staggerChildren:0.12',
  },
  {
    id: 'features-motion-bento-reveal',
    category: 'features-motion', dna: ['framer', 'stripe'],
    animationType: ['fadeUp', 'stagger', 'scaleIn'], duration: 300, delay: 0, stagger: 80,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Bento grid: large card reveals first, smaller cards stagger after. Cards scale 0.96→1 with fadeUp.',
    codeHint: 'large-card: delay:0; small-cards: staggerChildren:0.08 after large; all scale:0.96→1',
  },
  {
    id: 'features-motion-apple-section',
    category: 'features-motion', dna: ['apple'],
    animationType: ['fadeUp', 'scaleIn'], duration: 350, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple section: headline reveals first, then 3 feature columns slide up together with slight stagger.',
    codeHint: 'headline: delay:0; columns: staggerChildren:0.09 delayChildren:0.15; all y:16→0 scale:0.97→1',
  },
  {
    id: 'features-motion-notion-minimal',
    category: 'features-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.7,
    description: 'Notion: feature items fade in with almost no motion. Purely opacity. Editorial weight. Nothing distracts from content.',
    codeHint: 'opacity:0→1 duration:0.2; staggerChildren:0.06; no y or scale',
  },
  {
    id: 'features-motion-stripe-count-up',
    category: 'features-motion', dna: ['stripe', 'apple'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Stripe stats section: each stat card stagger-reveals. Numbers count up using useMotionValue + useTransform on scroll.',
    codeHint: 'staggerChildren:0.1; stat-card fadeUp; number: useMotionValue + useTransform scroll→value',
  },
  {
    id: 'features-motion-cursor-list',
    category: 'features-motion', dna: ['cursor', 'linear'],
    animationType: ['slideLeft', 'fade'], duration: 200, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor-style feature list: items slide from x:-6 with fast fade. Dense, developer-focused. No cards.',
    codeHint: 'x:-6→0 opacity:0→1 duration:0.2; staggerChildren:0.05; no card wrapper',
  },
  {
    id: 'features-motion-vercel-grid',
    category: 'features-motion', dna: ['vercel'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel feature grid: pure opacity + slight y:8 per card. No scale. Monochrome — motion is invisible on purpose.',
    codeHint: 'y:8→0 opacity:0→1 duration:0.25; staggerChildren:0.07; viewport once:true',
  },
  {
    id: 'features-motion-raycast-row',
    category: 'features-motion', dna: ['raycast'],
    animationType: ['fadeUp', 'stagger'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.1,
    description: 'Raycast horizontal feature row: items stagger at 70ms. Fast entrance. Suits developer tool feature lists.',
    codeHint: 'row: staggerChildren:0.07; item: y:10→0 opacity:0→1 duration:0.25',
  },
  {
    id: 'features-motion-framer-hover-card',
    category: 'features-motion', dna: ['framer', 'apple'],
    animationType: ['scaleIn', 'fadeUp'], duration: 300, delay: 0, stagger: 100,
    intensity: 'high', qualityHint: 9.6,
    description: 'Feature cards with hover elevation: whileHover y:-4 scale:1.02 with box-shadow transition. Pairs with spring card entrance.',
    codeHint: 'whileHover={{ y:-4, scale:1.02 }} transition={{ type:"spring", stiffness:300, damping:20 }}',
  },
  {
    id: 'features-motion-stripe-scroll',
    category: 'features-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 350, delay: 0, stagger: 110,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe scroll-triggered: features reveal as user scrolls. useInView margin -100px. Section headline animates before cards.',
    codeHint: 'useInView margin:"-100px"; headline first; cards staggerChildren:0.11 delayChildren:0.2',
  },
  {
    id: 'features-motion-apple-icon-animate',
    category: 'features-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Apple feature icons rotate or scale on hover. Section reveals with smooth scale 0.95→1 stagger.',
    codeHint: 'icon whileHover: rotate:5 scale:1.1 spring; card entrance: scale:0.95→1 fadeUp stagger:0.09',
  },
  {
    id: 'features-motion-linear-divider',
    category: 'features-motion', dna: ['linear'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.1,
    description: 'Linear-style border-bottom divided feature list. Each row fades up. Top-to-bottom flow. No card hover.',
    codeHint: 'list: staggerChildren:0.08; row: y:8→0 opacity:0→1 duration:0.25; no whileHover',
  },
  {
    id: 'features-motion-framer-reveal-path',
    category: 'features-motion', dna: ['framer'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 400, delay: 0, stagger: 130,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer feature reveal with SVG path animation on icon. Cards stagger with spring. Premium interactive feel.',
    codeHint: 'SVG pathLength:0→1; card: spring entrance; staggerChildren:0.13; whileHover scale:1.04',
  },
  {
    id: 'features-motion-vercel-minimal',
    category: 'features-motion', dna: ['vercel', 'notion'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.8,
    description: 'Vercel/Notion minimal: features simply fade in with almost zero motion. Motion is structural, not decorative.',
    codeHint: 'opacity:0→1 duration:0.15; staggerChildren:0.05; no translate no scale',
  },
  {
    id: 'features-motion-stripe-grid-wave',
    category: 'features-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Stripe grid wave: cards in a 3-col grid stagger diagonally. Row 1 then row 2 then row 3 with 90ms each.',
    codeHint: 'custom delay per card: index * 0.09; y:20→0 opacity:0→1 duration:0.3',
  },
  {
    id: 'features-motion-apple-split',
    category: 'features-motion', dna: ['apple'],
    animationType: ['slideLeft', 'slideRight'], duration: 350, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Apple split feature: left text x:-16→0, right visual x:16→0. Simultaneous with smooth ease curve. No stagger needed.',
    codeHint: 'left: x:-16→0; right: x:16→0; both opacity:0→1 duration:0.35 ease:[0.25,0.46,0.45,0.94]',
  },
  {
    id: 'features-motion-cursor-code',
    category: 'features-motion', dna: ['cursor', 'raycast'],
    animationType: ['fadeUp', 'stagger'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Developer tool code-block features: code panels slide up with fast stagger. Monospace aesthetic.',
    codeHint: 'code-panel: y:12→0 opacity:0→1 duration:0.2; staggerChildren:0.06',
  },
  {
    id: 'features-motion-raycast-list-hover',
    category: 'features-motion', dna: ['raycast', 'linear'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Raycast feature row hover: whileHover x:2 with fast spring. Subtle leftward nudge on hover.',
    codeHint: 'whileHover={{ x:2 }} transition={{ type:"spring", stiffness:400, damping:25 }}',
  },
  {
    id: 'features-motion-framer-3d-tilt',
    category: 'features-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeUp'], duration: 350, delay: 0, stagger: 100,
    intensity: 'high', qualityHint: 9.8,
    description: 'Framer 3D card tilt on hover using useMotionValue for rotateX/rotateY. Cards entrance with spring. Premium interactive experience.',
    codeHint: 'useMotionValue x,y; rotateX/Y transform; whileHover triggers tilt via onMouseMove',
  },
];

// ── PRICING MOTION — 18 references ────────────────────────────────────────────
const pricingMotionRefs: MotionReference[] = [
  {
    id: 'pricing-motion-scale-reveal',
    category: 'pricing-motion', dna: ['stripe', 'framer', 'apple'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Pricing cards scale from 0.94→1.0 with fadeUp. Featured plan scales last at larger scale. Stagger left→center→right.',
    codeHint: 'staggerChildren:0.1; card: scale:0.94→1 y:20→0 opacity:0→1; featured-card: scale:0.92→1 delay extra',
  },
  {
    id: 'pricing-motion-linear-tabs',
    category: 'pricing-motion', dna: ['linear', 'vercel'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.0,
    description: 'Monthly/annual toggle with AnimatePresence. Selected panel cross-fades. Cards fade in together. No scale.',
    codeHint: 'AnimatePresence mode:"wait"; panel exit: opacity:0 duration:0.1; enter: opacity:1 duration:0.2',
  },
  {
    id: 'pricing-motion-framer-featured',
    category: 'pricing-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeUp'], duration: 400, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer: featured plan springs in with scale:0.85→1. Badge on featured pops in with spring. CTA button pulses once.',
    codeHint: 'featured: spring stiffness:200 damping:18 scale:0.85→1; badge: spring scale:0→1; cta: initial pulse',
  },
  {
    id: 'pricing-motion-stripe-gradient-reveal',
    category: 'pricing-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 350, delay: 0, stagger: 110,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Stripe pricing: gradient border reveals on featured card via clip-path animation. Cards stagger into view.',
    codeHint: 'clipPath: inset(100%→0%); staggerChildren:0.11; all cards y:24→0 opacity:0→1',
  },
  {
    id: 'pricing-motion-apple-elegant',
    category: 'pricing-motion', dna: ['apple'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 300, delay: 80, stagger: 90,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple pricing: smooth reveal with slight scale. Feature list items stagger after card appears.',
    codeHint: 'card: scale:0.96→1 y:12→0 duration:0.3 delayChildren:0.08; features: staggerChildren:0.09',
  },
  {
    id: 'pricing-motion-notion-static',
    category: 'pricing-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion: cards fade in simultaneously. Feature list items appear 60ms apart. No scale, no translate.',
    codeHint: 'opacity:0→1 duration:0.2; features staggerChildren:0.06',
  },
  {
    id: 'pricing-motion-cursor-minimal',
    category: 'pricing-motion', dna: ['cursor', 'linear'],
    animationType: ['fadeUp', 'fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor pricing: fast fade with y:8. Developer-tool price cards feel sharp, not decorative.',
    codeHint: 'y:8→0 opacity:0→1 duration:0.2; stagger 0.06',
  },
  {
    id: 'pricing-motion-toggle-switch',
    category: 'pricing-motion', dna: ['stripe', 'apple', 'framer'],
    animationType: ['fade', 'scaleIn'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Billing toggle animation: Switch component animates thumb; prices cross-fade with AnimatePresence; savings badge pops.',
    codeHint: 'AnimatePresence; price: exit opacity:0 y:-4; enter opacity:1 y:0; savings badge scale:0→1 spring',
  },
  {
    id: 'pricing-motion-vercel-border',
    category: 'pricing-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel: cards fade in. Border on featured plan has subtle animated glow via CSS (not framer). Clean, monochrome.',
    codeHint: 'opacity:0→1 duration:0.25; stagger 0.07; featured: CSS animate border-color glow only',
  },
  {
    id: 'pricing-motion-raycast-grid',
    category: 'pricing-motion', dna: ['raycast'],
    animationType: ['fadeUp', 'stagger'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.0,
    description: 'Raycast 3-tier grid stagger. Each plan y:10→0. Feature list items stagger inside each card.',
    codeHint: 'cards stagger:0.08; inner features stagger:0.05 delayChildren after card visible',
  },
  {
    id: 'pricing-motion-framer-cta-hover',
    category: 'pricing-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 100,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer: CTA inside each plan has whileHover scale:1.04 + gradient shimmer. whileTap scale:0.96. Spring.',
    codeHint: 'whileHover={{ scale:1.04 }} whileTap={{ scale:0.96 }} spring stiffness:400 damping:25',
  },
  {
    id: 'pricing-motion-stripe-list-reveal',
    category: 'pricing-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 100, stagger: 60,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe: feature checkmarks in pricing list stagger in after card entrance. Each feature appears 60ms apart.',
    codeHint: 'card entrance first; then feature-list staggerChildren:0.06 delayChildren after card visible',
  },
  {
    id: 'pricing-motion-apple-focus',
    category: 'pricing-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fade'], duration: 350, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Apple: featured plan grows in viewport. Non-featured slightly smaller scale. Focus hierarchy in animation.',
    codeHint: 'featured: scale:0.9→1.05 then settle; side: scale:0.92→1; simultaneous but different targets',
  },
  {
    id: 'pricing-motion-linear-instant',
    category: 'pricing-motion', dna: ['linear'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.9,
    description: 'Linear: instant-feeling pricing reveal. 150ms opacity only. No oversell. Content is the product.',
    codeHint: 'opacity:0→1 duration:0.15; stagger 0.05',
  },
  {
    id: 'pricing-motion-framer-spotlight',
    category: 'pricing-motion', dna: ['framer', 'stripe'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 400, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.8,
    description: 'Framer/Stripe spotlight: featured plan has animated radial gradient spotlight on hover. Cards stagger with spring.',
    codeHint: 'featured: onMouseMove radial-gradient follows cursor; entrance spring; staggerChildren:0.12',
  },
  {
    id: 'pricing-motion-vercel-switch',
    category: 'pricing-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 8.9,
    description: 'Vercel toggle: AnimatePresence monthly/annual cross-fade. No bounce. Monochrome restraint.',
    codeHint: 'AnimatePresence mode:"wait"; 0.2s cross-fade; no scale',
  },
  {
    id: 'pricing-motion-cursor-code-toggle',
    category: 'pricing-motion', dna: ['cursor'],
    animationType: ['fade', 'slideLeft'], duration: 200, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.8,
    description: 'Cursor: pricing toggle is minimal. Plans slide from left on switch. Code-editor aesthetic.',
    codeHint: 'x:-8→0 opacity:0→1 duration:0.2 on plan switch; no card animations',
  },
  {
    id: 'pricing-motion-reduced-motion',
    category: 'pricing-motion', dna: ['stripe', 'framer', 'apple', 'linear', 'vercel', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced motion: all pricing animations collapse to opacity only. useReducedMotion gate always required.',
    codeHint: 'const rm = useReducedMotion(); if(rm) skip stagger, skip scale, use only opacity:0→1',
  },
];

// ── TESTIMONIALS MOTION — 18 references ───────────────────────────────────────
const testimonialsMotionRefs: MotionReference[] = [
  {
    id: 'testimonials-motion-fade-sequence',
    category: 'testimonials-motion', dna: ['stripe', 'apple'],
    animationType: ['fade', 'stagger'], duration: 300, delay: 0, stagger: 120,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Testimonial cards fade in sequence. Each card 120ms after previous. Avatar appears before text.',
    codeHint: 'staggerChildren:0.12; avatar: opacity:0→1 first; name+quote follow staggered',
  },
  {
    id: 'testimonials-motion-framer-carousel',
    category: 'testimonials-motion', dna: ['framer'],
    animationType: ['slideLeft', 'fade'], duration: 350, delay: 0, stagger: 0,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer carousel: testimonials slide left/right with drag support. AnimatePresence handles exits.',
    codeHint: 'drag:"x"; AnimatePresence; exit x:-100% opacity:0; enter x:100%→0 opacity:1',
  },
  {
    id: 'testimonials-motion-linear-minimal',
    category: 'testimonials-motion', dna: ['linear', 'vercel'],
    animationType: ['fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear-style testimonials: each card fades up simply. No hover effects. Clean editorial.',
    codeHint: 'y:12→0 opacity:0→1 duration:0.25; stagger 0.08; no hover',
  },
  {
    id: 'testimonials-motion-apple-warm',
    category: 'testimonials-motion', dna: ['apple'],
    animationType: ['fadeUp', 'stagger', 'scaleIn'], duration: 300, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Apple: testimonial cards feel warm. Slight scale 0.97→1. Avatar pops in first with spring. Quote follows.',
    codeHint: 'avatar: spring scale:0→1; quote: fadeUp y:8 delay:0.1; stagger 0.09 per card',
  },
  {
    id: 'testimonials-motion-stripe-scroll',
    category: 'testimonials-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 350, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe: horizontal scroll testimonial row. Cards stagger in. Auto-scrolling with useAnimationFrame.',
    codeHint: 'useAnimationFrame for auto-scroll; each card initially hidden then stagger on viewport',
  },
  {
    id: 'testimonials-motion-notion-simple',
    category: 'testimonials-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.7,
    description: 'Notion: testimonials appear with opacity only. Simple 3-column layout. No hover effects.',
    codeHint: 'opacity:0→1 duration:0.2; stagger 0.06; no y no scale',
  },
  {
    id: 'testimonials-motion-framer-marquee',
    category: 'testimonials-motion', dna: ['framer', 'stripe'],
    animationType: ['slideLeft'], duration: 0, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Framer marquee: testimonials scroll continuously x:0→-50% loop. Hover pauses. Premium infinite scroll.',
    codeHint: 'animate={{ x:[0,-50%] }} transition={{ duration:30, repeat:Infinity, ease:"linear" }}; hover pause',
  },
  {
    id: 'testimonials-motion-cursor-minimal',
    category: 'testimonials-motion', dna: ['cursor', 'linear'],
    animationType: ['fadeUp'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.8,
    description: 'Cursor: compact testimonial quotes. Single column. Each quote fades up fast. Matches terminal aesthetic.',
    codeHint: 'y:8→0 opacity:0→1 duration:0.2; stagger 0.06',
  },
  {
    id: 'testimonials-motion-vercel-opacity',
    category: 'testimonials-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel: testimonials appear via opacity sequence. Monochrome — motion is invisible as design intention.',
    codeHint: 'opacity:0→1 duration:0.25; stagger 0.07; monochrome card style',
  },
  {
    id: 'testimonials-motion-apple-hover-lift',
    category: 'testimonials-motion', dna: ['apple'],
    animationType: ['fadeUp', 'scaleIn'], duration: 300, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple hover: testimonial cards lift y:-4 with shadow deepening on hover. whileHover spring.',
    codeHint: 'whileHover={{ y:-4 }} transition={{ type:"spring", stiffness:300, damping:20 }}',
  },
  {
    id: 'testimonials-motion-stripe-quote',
    category: 'testimonials-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 110,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Stripe: large quote mark appears first with scaleIn, then text fades up. Avatar last. Premium editorial.',
    codeHint: 'quote-mark: scale:0→1 spring first; text: y:12→0 duration:0.3 delay:0.1; avatar last delay:0.2',
  },
  {
    id: 'testimonials-motion-raycast-row',
    category: 'testimonials-motion', dna: ['raycast'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 8.9,
    description: 'Raycast: inline testimonial quotes with subtle stagger. Developer-focused. Clean.',
    codeHint: 'y:8→0 opacity:0→1; stagger 0.07',
  },
  {
    id: 'testimonials-motion-framer-masonry',
    category: 'testimonials-motion', dna: ['framer'],
    animationType: ['fadeUp', 'stagger', 'scaleIn'], duration: 350, delay: 0, stagger: 80,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer masonry testimonials: cards stagger column by column. Left col then middle then right. Spring entrance.',
    codeHint: 'custom delay: colIndex*0.15 + rowIndex*0.08; spring entrance per card',
  },
  {
    id: 'testimonials-motion-notion-editorial',
    category: 'testimonials-motion', dna: ['notion'],
    animationType: ['fadeDown'], duration: 200, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.7,
    description: 'Notion editorial: testimonials fade from y:-6 (down from above). Subtle editorial gravity.',
    codeHint: 'y:-6→0 opacity:0→1 duration:0.2; stagger 0.05',
  },
  {
    id: 'testimonials-motion-stripe-avatar-pop',
    category: 'testimonials-motion', dna: ['stripe', 'apple'],
    animationType: ['scaleIn', 'stagger'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Avatar images spring in with scale:0.8→1 then quote fades. Humanizes the testimonial section.',
    codeHint: 'avatar: scale:0.8→1 spring stiffness:250 damping:20; quote: delay:0.15 fadeUp',
  },
  {
    id: 'testimonials-motion-linear-divider',
    category: 'testimonials-motion', dna: ['linear'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear horizontal divider testimonials. Each row with quote + avatar fades up. Minimal, focused.',
    codeHint: 'row: y:8→0 opacity:0→1; stagger 0.08; border-bottom separates each',
  },
  {
    id: 'testimonials-motion-framer-drag-scroll',
    category: 'testimonials-motion', dna: ['framer'],
    animationType: ['slideLeft', 'fadeUp'], duration: 300, delay: 0, stagger: 100,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer draggable testimonials row: drag="x" dragConstraints. Cards snap. Initial stagger entrance.',
    codeHint: 'motion.div drag="x" dragConstraints={{ left: -(total-container), right:0 }}; snap via dragElastic',
  },
  {
    id: 'testimonials-motion-apple-stagger-warm',
    category: 'testimonials-motion', dna: ['apple'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 350, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Apple warm: testimonials enter with warm easing curve. Avatar circles scale in. Quote and name stagger.',
    codeHint: 'ease:[0.34,1.56,0.64,1] spring-like cubic; avatar scale:0→1; stagger 0.09',
  },
];

// ── FAQ MOTION — 15 references ─────────────────────────────────────────────────
const faqMotionRefs: MotionReference[] = [
  {
    id: 'faq-motion-accordion-smooth',
    category: 'faq-motion', dna: ['stripe', 'apple', 'linear'],
    animationType: ['fadeDown', 'scaleIn'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Accordion answer reveals with height animation. Content fades in as height expands. shadcn Accordion with Framer.',
    codeHint: 'AnimatePresence; height:0→auto duration:0.25; content opacity:0→1 delay:0.05',
  },
  {
    id: 'faq-motion-framer-spring-open',
    category: 'faq-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeDown'], duration: 300, delay: 0, stagger: 0,
    intensity: 'high', qualityHint: 9.5,
    description: 'Framer: accordion opens with spring. Chevron rotates 180° with spring. Content fades in with slight scaleY.',
    codeHint: 'chevron: rotate:0→180 spring; content: scaleY:0.8→1 opacity:0→1 spring stiffness:200 damping:20',
  },
  {
    id: 'faq-motion-linear-clean',
    category: 'faq-motion', dna: ['linear', 'vercel'],
    animationType: ['fadeDown', 'fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear: FAQ items stagger in on mount. Accordion height animates. Chevron rotates 90°. Clean.',
    codeHint: 'items stagger 0.06 on mount; accordion: height animate duration:0.2; chevron rotate:0→90',
  },
  {
    id: 'faq-motion-notion-minimal',
    category: 'faq-motion', dna: ['notion'],
    animationType: ['fade', 'fadeDown'], duration: 150, delay: 0, stagger: 40,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion: FAQ barely animates. Height transition via CSS max-height. Opacity only for content.',
    codeHint: 'CSS max-height transition; framer only for opacity:0→1 on content; stagger mount 0.04',
  },
  {
    id: 'faq-motion-apple-smooth',
    category: 'faq-motion', dna: ['apple'],
    animationType: ['fadeDown', 'scaleIn'], duration: 300, delay: 0, stagger: 70,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple: FAQ accordion with smooth height reveal. Icon rotates 45°. Easing feels premium and intentional.',
    codeHint: 'height auto ease:[0.25,0.46,0.45,0.94]; icon rotate:0→45 same easing; content fade delay:0.1',
  },
  {
    id: 'faq-motion-stripe-grouped',
    category: 'faq-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 280, delay: 0, stagger: 70,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Stripe: FAQ groups stagger in. Each question fades up on viewport enter. Open/close with height + opacity.',
    codeHint: 'group stagger:0.07; question mount: y:8→0 opacity:0→1; accordion: height+opacity animate',
  },
  {
    id: 'faq-motion-cursor-code',
    category: 'faq-motion', dna: ['cursor', 'raycast'],
    animationType: ['fade', 'fadeDown'], duration: 200, delay: 0, stagger: 50,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor: FAQ items look like terminal entries. Minimal height animation. Items mount with fast fade.',
    codeHint: 'opacity:0→1 duration:0.2 stagger 0.05; accordion: height only no opacity',
  },
  {
    id: 'faq-motion-framer-hover-bg',
    category: 'faq-motion', dna: ['framer'],
    animationType: ['fade', 'scaleIn'], duration: 250, delay: 0, stagger: 80,
    intensity: 'high', qualityHint: 9.4,
    description: 'Framer: FAQ row background animates on hover via layoutId. Shared layout transition.',
    codeHint: 'layoutId="faq-bg"; whileHover triggers background motion; accordion spring height',
  },
  {
    id: 'faq-motion-vercel-border',
    category: 'faq-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.9,
    description: 'Vercel: FAQ items appear via opacity. Border-bottom shows active state via CSS. Height collapses instantly.',
    codeHint: 'mount: opacity:0→1 stagger 0.06; accordion: CSS height collapse only',
  },
  {
    id: 'faq-motion-apple-icon-rotate',
    category: 'faq-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Apple: + icon rotates 45° to become × on open. Height reveals with smooth curve. Micro-detail perfection.',
    codeHint: 'icon: rotate:0→45 duration:0.3 ease:"backOut"; height auto; content delay:0.1 fadeDown',
  },
  {
    id: 'faq-motion-stripe-search',
    category: 'faq-motion', dna: ['stripe'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 60,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Stripe FAQ with filter: filtered items exit/enter with AnimatePresence. Results animate in on filter.',
    codeHint: 'AnimatePresence; exit: opacity:0 y:-4 duration:0.1; enter: opacity:1 y:0 stagger 0.06',
  },
  {
    id: 'faq-motion-raycast-compact',
    category: 'faq-motion', dna: ['raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 40,
    intensity: 'low', qualityHint: 8.8,
    description: 'Raycast: ultra-compact FAQ with instant-feel. No height animation. Only content opacity.',
    codeHint: 'visibility toggle; content: opacity:0→1 duration:0.15; no stagger no height animation',
  },
  {
    id: 'faq-motion-linear-divider',
    category: 'faq-motion', dna: ['linear'],
    animationType: ['fadeDown', 'fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear: clean divider FAQ. Each item stagger-fades on mount. Height animates on toggle. Minimal.',
    codeHint: 'stagger mount 0.06; height: max-height CSS + framer opacity for content',
  },
  {
    id: 'faq-motion-framer-layout',
    category: 'faq-motion', dna: ['framer', 'apple'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 80,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer layout animation: FAQ items use layout prop so open state shifts siblings smoothly.',
    codeHint: 'motion.div layout; AnimatePresence; sibling shift is automatic with layout prop',
  },
  {
    id: 'faq-motion-reduced',
    category: 'faq-motion', dna: ['stripe', 'framer', 'apple', 'linear', 'vercel', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced motion: FAQ accordion uses instant height toggle. Only content opacity. No rotate, no spring.',
    codeHint: 'useReducedMotion: skip height animation; instant toggle; opacity:0→1 only',
  },
];

// ── DASHBOARD MOTION — 18 references ──────────────────────────────────────────
const dashboardMotionRefs: MotionReference[] = [
  {
    id: 'dashboard-motion-skeleton-reveal',
    category: 'dashboard-motion', dna: ['linear', 'vercel', 'cursor'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.2,
    description: 'Dashboard: Skeleton loaders fade out, content fades in. AnimatePresence handles loading→loaded transition.',
    codeHint: 'AnimatePresence; skeleton exit opacity:0; content enter opacity:1 stagger 0.06 duration:0.2',
  },
  {
    id: 'dashboard-motion-tab-slide',
    category: 'dashboard-motion', dna: ['stripe', 'apple', 'framer'],
    animationType: ['slideLeft', 'fade'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Dashboard tab switch: content slides left/right based on tab direction. AnimatePresence with mode="wait".',
    codeHint: 'direction state; enter: x:direction*20→0 opacity:1; exit: x:direction*-20 opacity:0; mode:"wait"',
  },
  {
    id: 'dashboard-motion-stats-count',
    category: 'dashboard-motion', dna: ['stripe', 'apple'],
    animationType: ['fade', 'scaleIn'], duration: 300, delay: 0, stagger: 80,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Dashboard stat cards: numbers count up using useMotionValue + motionValue.set(). Cards stagger in.',
    codeHint: 'useMotionValue; animate 0→target via useTransform; staggerChildren:0.08; card scaleIn',
  },
  {
    id: 'dashboard-motion-framer-sidebar',
    category: 'dashboard-motion', dna: ['framer'],
    animationType: ['slideLeft', 'fade'], duration: 300, delay: 0, stagger: 0,
    intensity: 'high', qualityHint: 9.5,
    description: 'Framer sidebar collapse/expand: width animation 240px→64px with spring. Menu labels fade out on collapse.',
    codeHint: 'sidebar: animate={{ width: isOpen?240:64 }} spring; labels: AnimatePresence fade',
  },
  {
    id: 'dashboard-motion-table-rows',
    category: 'dashboard-motion', dna: ['linear', 'cursor'],
    animationType: ['fadeUp', 'stagger'], duration: 200, delay: 0, stagger: 30,
    intensity: 'low', qualityHint: 9.1,
    description: 'DataTable rows stagger in on mount. Each row 30ms apart. Fast, clean. No hover effects on rows.',
    codeHint: 'rows: staggerChildren:0.03; row: y:4→0 opacity:0→1 duration:0.2',
  },
  {
    id: 'dashboard-motion-apple-cards',
    category: 'dashboard-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 300, delay: 0, stagger: 80,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple dashboard metric cards: stagger with scale:0.96→1. Smooth, premium metric reveal.',
    codeHint: 'card: scale:0.96→1 y:12→0 opacity:0→1 duration:0.3; staggerChildren:0.08',
  },
  {
    id: 'dashboard-motion-notification-slide',
    category: 'dashboard-motion', dna: ['stripe', 'linear'],
    animationType: ['slideLeft', 'fade'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Notification/toast: slides in from x:100% on arrival. AnimatePresence for exit. Stack with stagger.',
    codeHint: 'x:100%→0 opacity:0→1 duration:0.25; exit x:100% opacity:0; vertical stagger when multiple',
  },
  {
    id: 'dashboard-motion-vercel-metrics',
    category: 'dashboard-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 250, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel-style analytics dashboard: minimal fade for all elements. No scale. Data is the focus.',
    codeHint: 'opacity:0→1 stagger 0.06; no y no scale; chart bars animate width not opacity',
  },
  {
    id: 'dashboard-motion-framer-chart',
    category: 'dashboard-motion', dna: ['framer', 'stripe'],
    animationType: ['scaleIn', 'fade'], duration: 400, delay: 0, stagger: 0,
    intensity: 'high', qualityHint: 9.6,
    description: 'Chart bars animate height from 0→value using scaleY on viewport enter. Spring stiffness 150.',
    codeHint: 'bar: scaleY:0→1 origin-bottom spring stiffness:150 damping:20; delay per bar: index*0.04',
  },
  {
    id: 'dashboard-motion-cursor-rows',
    category: 'dashboard-motion', dna: ['cursor'],
    animationType: ['fade', 'fadeUp'], duration: 150, delay: 0, stagger: 25,
    intensity: 'low', qualityHint: 8.9,
    description: 'Cursor/dev tool: rows appear ultra-fast with tiny stagger. Terminal-inspired data reveal.',
    codeHint: 'row: opacity:0→1 y:2→0 duration:0.15; stagger 0.025',
  },
  {
    id: 'dashboard-motion-stripe-modal',
    category: 'dashboard-motion', dna: ['stripe', 'apple'],
    animationType: ['scaleIn', 'fade'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Dashboard modal/sheet: scale:0.95→1 with backdrop fade. AnimatePresence. Escape closes with reverse.',
    codeHint: 'backdrop: opacity:0→0.6; modal: scale:0.95→1 opacity:0→1 duration:0.25; exit reverse',
  },
  {
    id: 'dashboard-motion-raycast-command',
    category: 'dashboard-motion', dna: ['raycast', 'cursor'],
    animationType: ['scaleIn', 'fade'], duration: 200, delay: 0, stagger: 20,
    intensity: 'low', qualityHint: 9.1,
    description: 'Command palette opens with scale:0.96→1. Results stagger at 20ms. Closes with exit animation.',
    codeHint: 'command: scale:0.96→1 opacity:0→1 duration:0.2; results stagger:0.02; exit reverse',
  },
  {
    id: 'dashboard-motion-apple-hover-row',
    category: 'dashboard-motion', dna: ['apple'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.0,
    description: 'Apple table rows: whileHover background fade via motion.tr. Action buttons appear on hover.',
    codeHint: 'motion.tr whileHover={{ backgroundColor:"rgba(255,255,255,0.05)" }}; action buttons: opacity:0→1',
  },
  {
    id: 'dashboard-motion-linear-panel',
    category: 'dashboard-motion', dna: ['linear'],
    animationType: ['slideLeft', 'fade'], duration: 250, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.1,
    description: 'Linear detail panel: slides in from right x:32→0 when row selected. Sidebar-style panel.',
    codeHint: 'x:32→0 opacity:0→1 duration:0.25; AnimatePresence; exit x:32 opacity:0',
  },
  {
    id: 'dashboard-motion-framer-drag-kanban',
    category: 'dashboard-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 50,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer drag kanban cards: drag with spring reorder. whileDrag scale:1.05 z-index lift.',
    codeHint: 'drag="y"; whileDrag={{ scale:1.05 }}; Reorder.Group Reorder.Item from framer-motion',
  },
  {
    id: 'dashboard-motion-stripe-counter',
    category: 'dashboard-motion', dna: ['stripe'],
    animationType: ['fade', 'scaleIn'], duration: 350, delay: 0, stagger: 80,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe dashboard: revenue counter animates from $0 to target. Cards stagger in with scale.',
    codeHint: 'useMotionValue(0); animate({value:target}); display rounds during animation; stagger cards 0.08',
  },
  {
    id: 'dashboard-motion-notion-content',
    category: 'dashboard-motion', dna: ['notion'],
    animationType: ['fadeDown'], duration: 200, delay: 0, stagger: 40,
    intensity: 'low', qualityHint: 8.7,
    description: 'Notion: content areas fade from slightly above. Blocks appear top-to-bottom with 40ms gap.',
    codeHint: 'y:-4→0 opacity:0→1 duration:0.2; stagger 0.04',
  },
  {
    id: 'dashboard-motion-reduced',
    category: 'dashboard-motion', dna: ['stripe', 'framer', 'apple', 'linear', 'vercel', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced motion: skip all chart animations, skip tab slides, skip count-up. Load content instantly.',
    codeHint: 'useReducedMotion: disable chart scaleY, disable counter, disable tab slide; fade only',
  },
];

// ── CTA MOTION — 18 references ─────────────────────────────────────────────────
const ctaMotionRefs: MotionReference[] = [
  {
    id: 'cta-motion-scale-fade',
    category: 'cta-motion', dna: ['stripe', 'apple', 'framer'],
    animationType: ['scaleIn', 'fadeUp'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'CTA section: container scales 0.96→1 with fadeUp. Headline first, then subtext, then buttons.',
    codeHint: 'container scale:0.96→1 y:16→0 duration:0.3; staggerChildren:0.1; headline→sub→buttons',
  },
  {
    id: 'cta-motion-framer-button-pulse',
    category: 'cta-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fade'], duration: 400, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer: CTA primary button pulses once on mount (scale:1→1.05→1). Then whileHover scale:1.04.',
    codeHint: 'initial pulse: keyframes [1,1.05,1] duration:0.4; then whileHover: scale:1.04 spring',
  },
  {
    id: 'cta-motion-linear-clean',
    category: 'cta-motion', dna: ['linear', 'vercel'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.1,
    description: 'Linear CTA: headline fades up, buttons appear together. No scale. Button hover: slight brightness.',
    codeHint: 'headline y:12→0; buttons: group fade delay:0.15; whileHover: no scale just brightness via CSS',
  },
  {
    id: 'cta-motion-apple-emphasis',
    category: 'cta-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fadeUp', 'stagger'], duration: 350, delay: 0, stagger: 90,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Apple: CTA headline scales in with premium timing. Button springs in last. Elegant emphasis.',
    codeHint: 'h2: scale:0.95→1 ease:[0.25,0.46,0.45,0.94]; button: spring scale:0.9→1 delay:0.25',
  },
  {
    id: 'cta-motion-stripe-gradient',
    category: 'cta-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'scaleIn', 'stagger'], duration: 300, delay: 100, stagger: 110,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Stripe: CTA section background gradient animates on entry. Content stagger. Button glows on hover.',
    codeHint: 'background gradient animate via CSS; content: staggerChildren:0.11 y:20→0; button glow CSS',
  },
  {
    id: 'cta-motion-framer-spring-cta',
    category: 'cta-motion', dna: ['framer'],
    animationType: ['scaleIn', 'stagger'], duration: 350, delay: 0, stagger: 130,
    intensity: 'high', qualityHint: 9.8,
    description: 'Framer: full CTA section springs in from y:40. Both buttons spring sequentially. Arrow icon animates.',
    codeHint: 'container spring y:40→0; primary btn spring delay:0.1; secondary delay:0.2; arrow: x:0→4 on hover',
  },
  {
    id: 'cta-motion-notion-clean',
    category: 'cta-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion: CTA just fades in. Pure editorial. Button has no motion, only CSS hover state.',
    codeHint: 'opacity:0→1 duration:0.2; stagger 0.06; no whileHover on button',
  },
  {
    id: 'cta-motion-cursor-arrow',
    category: 'cta-motion', dna: ['cursor', 'linear'],
    animationType: ['fade', 'slideLeft'], duration: 200, delay: 0, stagger: 70,
    intensity: 'low', qualityHint: 9.0,
    description: 'Cursor: CTA button arrow icon slides right on hover (whileHover). Fast, terminal-precise.',
    codeHint: 'arrow: whileHover={{ x:4 }} transition={{ type:"spring", stiffness:400, damping:25 }}',
  },
  {
    id: 'cta-motion-vercel-simple',
    category: 'cta-motion', dna: ['vercel'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.0,
    description: 'Vercel: CTA text and buttons fade up together. Monochrome. No scale. Sharp minimal entrance.',
    codeHint: 'y:10→0 opacity:0→1 duration:0.25; buttons together delay:0.1',
  },
  {
    id: 'cta-motion-apple-glow',
    category: 'cta-motion', dna: ['apple'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple: primary CTA button has animated gradient border on hover. Smooth glow emerges.',
    codeHint: 'whileHover gradient border via CSS transition; button scale:1→1.02 spring on hover',
  },
  {
    id: 'cta-motion-stripe-reveal',
    category: 'cta-motion', dna: ['stripe'],
    animationType: ['fadeUp', 'stagger'], duration: 300, delay: 80, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe CTA: social proof (avatar row) stacks in with spring before headline. Reversal of typical order.',
    codeHint: 'avatars spring first delay:0; headline: delay:0.15; buttons: delay:0.3',
  },
  {
    id: 'cta-motion-framer-magnetic',
    category: 'cta-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fade'], duration: 300, delay: 0, stagger: 100,
    intensity: 'high', qualityHint: 9.8,
    description: 'Framer magnetic button: onMouseMove makes button follow cursor slightly. whileTap scale:0.95.',
    codeHint: 'useMotionValue x,y; button: style={{ x,y }} onMouseMove updates; whileTap scale:0.95',
  },
  {
    id: 'cta-motion-raycast-terminal',
    category: 'cta-motion', dna: ['raycast', 'cursor'],
    animationType: ['fade', 'fadeUp'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 9.0,
    description: 'Raycast: CTA with kbd shortcut hint. Hint badge fades in last. Terminal-appropriate brevity.',
    codeHint: 'headline: y:8→0 opacity:1; kbd badge: delay:0.2 opacity:0→1; no scale on button',
  },
  {
    id: 'cta-motion-linear-button-hover',
    category: 'cta-motion', dna: ['linear'],
    animationType: ['fade', 'fadeUp'], duration: 250, delay: 0, stagger: 80,
    intensity: 'low', qualityHint: 9.1,
    description: 'Linear: CTA button arrow shifts x:2 on hover with spring. Very subtle. Linear-brand precision.',
    codeHint: 'arrow-icon: whileHover={{ x:2 }} spring stiffness:400; button itself no scale',
  },
  {
    id: 'cta-motion-stripe-counter',
    category: 'cta-motion', dna: ['stripe', 'apple'],
    animationType: ['scaleIn', 'fade', 'stagger'], duration: 300, delay: 0, stagger: 100,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Stripe: CTA section has animated trust counter (e.g. "10,000+ teams") incrementing on viewport enter.',
    codeHint: 'counter: useMotionValue 0→10000; ceil/format in render; enters viewport triggers animate',
  },
  {
    id: 'cta-motion-framer-backdrop',
    category: 'cta-motion', dna: ['framer', 'stripe'],
    animationType: ['scaleIn', 'fadeUp'], duration: 400, delay: 0, stagger: 120,
    intensity: 'high', qualityHint: 9.7,
    description: 'Framer: CTA section has animated backdrop (particles or grid lines animate in). Content over.',
    codeHint: 'backdrop particles: staggerChildren:0.03; grid lines: pathLength animate; content over top',
  },
  {
    id: 'cta-motion-notion-button',
    category: 'cta-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 60,
    intensity: 'low', qualityHint: 8.8,
    description: 'Notion: CTA button has no motion effects. Pure editorial — hover via CSS only. Content is the call.',
    codeHint: 'opacity:0→1 on section mount; no whileHover on button; CSS :hover for styling only',
  },
  {
    id: 'cta-motion-reduced',
    category: 'cta-motion', dna: ['stripe', 'framer', 'apple', 'linear', 'vercel', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced motion: CTA appears instantly with opacity only. No scale, no pulse, no magnetic.',
    codeHint: 'useReducedMotion: instant opacity; disable pulse, magnetic, scale; CSS hover only',
  },
];

// ── NAVBAR MOTION — 18 references ─────────────────────────────────────────────
const navbarMotionRefs: MotionReference[] = [
  {
    id: 'navbar-motion-scroll-hide',
    category: 'navbar-motion', dna: ['linear', 'vercel', 'stripe', 'apple'],
    animationType: ['fadeUp', 'slideLeft'], duration: 250, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.2,
    description: 'Navbar hides on scroll-down, reveals on scroll-up using useScroll + useMotionValue. Classic UX pattern.',
    codeHint: 'useScroll; useVelocity; animate={{ y: scrollingDown ? -64 : 0 }} spring',
  },
  {
    id: 'navbar-motion-framer-dropdown',
    category: 'navbar-motion', dna: ['framer', 'stripe'],
    animationType: ['scaleIn', 'fadeDown'], duration: 250, delay: 0, stagger: 40,
    intensity: 'high', qualityHint: 9.5,
    description: 'Framer: NavigationMenu dropdown animates scale:0.95→1 from transform-origin top. Links stagger in.',
    codeHint: 'dropdown: scale:0.95→1 y:-4→0 opacity:0→1; links stagger:0.04; transformOrigin:"top center"',
  },
  {
    id: 'navbar-motion-linear-border',
    category: 'navbar-motion', dna: ['linear'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear: navbar border-bottom appears when scrolled past threshold. Opacity 0→1 with useScroll.',
    codeHint: 'borderOpacity: useTransform(scrollY, [0,50], [0,1]); navbar blur on scroll',
  },
  {
    id: 'navbar-motion-apple-blur',
    category: 'navbar-motion', dna: ['apple'],
    animationType: ['fade'], duration: 300, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.3,
    description: 'Apple: backdrop-blur intensifies as user scrolls. Background opacity 0→0.8. Logo fades in on scroll.',
    codeHint: 'backdropBlur: useTransform(scrollY, [0,80], [0,12]); bg-opacity similar transform',
  },
  {
    id: 'navbar-motion-stripe-sticky',
    category: 'navbar-motion', dna: ['stripe'],
    animationType: ['fade', 'slideLeft'], duration: 250, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Stripe: navbar background fades in on scroll. CTA button in nav animates from 0→1 width when scrolled.',
    codeHint: 'bgOpacity: useTransform(scrollY, [0,100], [0,1]); cta: width auto animate after scroll',
  },
  {
    id: 'navbar-motion-mobile-sheet',
    category: 'navbar-motion', dna: ['linear', 'stripe', 'apple', 'framer'],
    animationType: ['slideLeft', 'fade'], duration: 300, delay: 0, stagger: 60,
    intensity: 'medium', qualityHint: 9.4,
    description: 'Mobile sheet open: Sheet slides from left x:-100%→0. Nav items stagger in inside sheet.',
    codeHint: 'shadcn Sheet side:"left"; items inside: staggerChildren:0.06; y:8→0 opacity:1',
  },
  {
    id: 'navbar-motion-vercel-minimal',
    category: 'navbar-motion', dna: ['vercel'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 8.9,
    description: 'Vercel: navbar barely animates. Only blur on scroll. Links hover via CSS. Motion is almost absent.',
    codeHint: 'blur: useTransform(scrollY, [0,50], [0,8]); no link motion; CSS hover only',
  },
  {
    id: 'navbar-motion-framer-indicator',
    category: 'navbar-motion', dna: ['framer'],
    animationType: ['slideLeft', 'scaleIn'], duration: 250, delay: 0, stagger: 0,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer: active nav link has animated underline indicator using layoutId. Smooth between states.',
    codeHint: 'active-indicator: motion.div layoutId="nav-indicator"; position under active link; spring',
  },
  {
    id: 'navbar-motion-cursor-terminal',
    category: 'navbar-motion', dna: ['cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 8.8,
    description: 'Cursor: navbar has minimal entry. Items just appear. Mobile: simple slide from top.',
    codeHint: 'mobile: y:-8→0 opacity:0→1 duration:0.15; no scroll effects; links CSS hover only',
  },
  {
    id: 'navbar-motion-notion-light',
    category: 'navbar-motion', dna: ['notion'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 8.7,
    description: 'Notion light: navbar fades in on page load. No scroll behavior. Editorial, borderless.',
    codeHint: 'opacity:0→1 duration:0.2 on mount; no scroll transform; CSS hover for links',
  },
  {
    id: 'navbar-motion-apple-links',
    category: 'navbar-motion', dna: ['apple'],
    animationType: ['fade', 'scaleIn'], duration: 250, delay: 0, stagger: 40,
    intensity: 'medium', qualityHint: 9.2,
    description: 'Apple: on page load nav links fade in staggered. Logo appears first. Premium entrance.',
    codeHint: 'logo: opacity:0→1 delay:0; links: stagger 0.04 each opacity:0→1; cta-btn: last delay:0.2',
  },
  {
    id: 'navbar-motion-raycast-blur',
    category: 'navbar-motion', dna: ['raycast'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.0,
    description: 'Raycast: glass-blur navbar appears on scroll. Ultra-minimal. Commands in nav animate with kbd hints.',
    codeHint: 'bg-opacity: useTransform(scrollY,[0,60],[0,0.9]); blur increases; no link animation',
  },
  {
    id: 'navbar-motion-stripe-mega-menu',
    category: 'navbar-motion', dna: ['stripe', 'apple'],
    animationType: ['fadeDown', 'scaleIn', 'stagger'], duration: 250, delay: 0, stagger: 40,
    intensity: 'medium', qualityHint: 9.5,
    description: 'Stripe mega-menu: full-width dropdown with staggered category columns. Each col 40ms apart.',
    codeHint: 'megamenu: y:-8→0 opacity:0→1; cols stagger:0.04; background panel scale:0.98→1',
  },
  {
    id: 'navbar-motion-framer-hamburger',
    category: 'navbar-motion', dna: ['framer'],
    animationType: ['scaleIn', 'fadeUp'], duration: 300, delay: 0, stagger: 60,
    intensity: 'high', qualityHint: 9.5,
    description: 'Framer: hamburger icon morphs (3 lines → X) via SVG path animation. Mobile menu slides from top.',
    codeHint: 'top-line: y and rotate variants; mid-line: opacity; bot-line: y and rotate; menu: y:-100%→0',
  },
  {
    id: 'navbar-motion-linear-scroll-fade',
    category: 'navbar-motion', dna: ['linear', 'cursor'],
    animationType: ['fade'], duration: 200, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 9.0,
    description: 'Linear: navbar bg materializes on scroll via opacity transform. Border appears. No link animation.',
    codeHint: 'bgOpacity: useTransform(scrollY,[0,30],[0,1]); borderOpacity same; mount: initial opacity:0→1',
  },
  {
    id: 'navbar-motion-apple-active',
    category: 'navbar-motion', dna: ['apple'],
    animationType: ['fade', 'scaleIn'], duration: 200, delay: 0, stagger: 0,
    intensity: 'medium', qualityHint: 9.1,
    description: 'Apple: active nav link has a dot indicator beneath that scales in. Hover: slight y:-1 spring.',
    codeHint: 'active-dot: scale:0→1 spring; link hover: whileHover y:-1 spring stiffness:400',
  },
  {
    id: 'navbar-motion-framer-scroll-reveal',
    category: 'navbar-motion', dna: ['framer', 'stripe'],
    animationType: ['fadeDown', 'fade', 'stagger'], duration: 300, delay: 0, stagger: 50,
    intensity: 'high', qualityHint: 9.6,
    description: 'Framer: on page load, navbar slides down from y:-16 with spring. Links stagger after.',
    codeHint: 'nav: y:-16→0 spring stiffness:200 damping:20; links stagger:0.05 after nav complete',
  },
  {
    id: 'navbar-motion-reduced',
    category: 'navbar-motion', dna: ['stripe', 'framer', 'apple', 'linear', 'vercel', 'notion', 'cursor', 'raycast'],
    animationType: ['fade'], duration: 150, delay: 0, stagger: 0,
    intensity: 'low', qualityHint: 10.0,
    description: 'Reduced motion: all navbar animation disabled. Static render. Scroll effects use opacity only.',
    codeHint: 'useReducedMotion: skip y transforms, skip stagger, disable scroll-hide; opacity only',
  },
];

// ── COMBINED CORPUS ────────────────────────────────────────────────────────────
export const MOTION_CORPUS: MotionReference[] = [
  ...heroMotionRefs,
  ...featuresMotionRefs,
  ...pricingMotionRefs,
  ...testimonialsMotionRefs,
  ...faqMotionRefs,
  ...dashboardMotionRefs,
  ...ctaMotionRefs,
  ...navbarMotionRefs,
];

// ── Motion DNA profiles — intensity × DNA ─────────────────────────────────────
export const MOTION_DNA_PROFILES: Record<string, { intensity: MotionIntensity; allowedTypes: AnimationType[]; maxDuration: number; stagger: boolean }> = {
  'bold-motion':       { intensity: 'high',   allowedTypes: ['fade','fadeUp','fadeDown','slideLeft','slideRight','scaleIn','stagger'], maxDuration: 400, stagger: true },
  'premium-gradient':  { intensity: 'medium', allowedTypes: ['fade','fadeUp','scaleIn','stagger'], maxDuration: 350, stagger: true },
  'monochrome':        { intensity: 'low',    allowedTypes: ['fade','fadeUp'], maxDuration: 250, stagger: false },
  'minimal-flat':      { intensity: 'low',    allowedTypes: ['fade','fadeUp'], maxDuration: 250, stagger: true },
  'editorial':         { intensity: 'low',    allowedTypes: ['fade'], maxDuration: 200, stagger: false },
  'dev-minimal':       { intensity: 'low',    allowedTypes: ['fade','fadeUp','slideLeft'], maxDuration: 200, stagger: true },
  'academic-clean':    { intensity: 'low',    allowedTypes: ['fade','fadeUp'], maxDuration: 200, stagger: false },
  'warm-organic':      { intensity: 'medium', allowedTypes: ['fade','fadeUp','scaleIn','stagger'], maxDuration: 300, stagger: true },
  'luxury-editorial':  { intensity: 'medium', allowedTypes: ['fade','fadeUp','scaleIn'], maxDuration: 350, stagger: true },
};

// ── Map design language → motion DNA label ────────────────────────────────────
export function getMotionDNAForDesignLanguage(designLanguage: string): MotionDNA {
  const map: Record<string, MotionDNA> = {
    'bold-motion':      'framer',
    'premium-gradient': 'stripe',
    'monochrome':       'vercel',
    'minimal-flat':     'linear',
    'editorial':        'notion',
    'dev-minimal':      'cursor',
    'academic-clean':   'raycast',
    'warm-organic':     'apple',
    'luxury-editorial': 'apple',
  };
  return map[designLanguage] ?? 'linear';
}
