// ── V7.2.2 Section-Level Design Corpus ───────────────────────────────────────
// 260 design references (105 existing + 155 new) indexed by section type.
// Extends designCorpus.ts with a `footer` section type and deeper per-section coverage.

import { DESIGN_CORPUS, type DesignReference, type DesignStyle } from './designCorpus.js';

// ── Section type — extends DesignCategory with footer ─────────────────────────
export type SectionType =
  | 'hero' | 'features' | 'pricing' | 'testimonials'
  | 'dashboard' | 'faq' | 'cta' | 'navbar' | 'footer';

export const ALL_SECTION_TYPES: SectionType[] = [
  'hero', 'features', 'pricing', 'testimonials',
  'dashboard', 'faq', 'cta', 'navbar', 'footer',
];

// SectionRef extends DesignReference — same shape, wider category type
export type SectionRef = Omit<DesignReference, 'category'> & { category: SectionType };

// ── Compact factory ────────────────────────────────────────────────────────────
function r(
  id: string, cat: SectionType, ind: string[], st: DesignStyle[],
  layout: string, tags: string[], desc: string, cids: string[], q: number,
): SectionRef {
  return { id, category: cat, industry: ind, style: st, layout, tags, description: desc, componentIds: cids, qualityHint: q };
}

// ── 155 NEW references ────────────────────────────────────────────────────────

// HERO — 5 new (existing: 25 → total: 30)
const newHeroRefs: SectionRef[] = [
  r('hero-full-viewport-video', 'hero', ['media', 'agency', 'startup'], ['framer', 'cursor'], 'full-viewport-video', ['video-bg', 'overlay-text', 'centered', 'dark', 'full-bleed'], 'Full-viewport auto-play muted video background with centered overlay headline and ghost button CTA.', ['hero-video-v2'], 8.8),
  r('hero-dark-angled', 'hero', ['saas', 'enterprise', 'security'], ['linear', 'vercel'], 'dark-angled', ['dark', 'angled-divider', 'split', 'geometric', 'high-contrast'], 'Dark hero with angled bottom divider, left-aligned headline, product screenshot, and accent border CTA.', ['hero-dark-angled-v1'], 8.7),
  r('hero-product-3d', 'hero', ['saas', 'developer', 'ai'], ['stripe', 'framer'], 'centered-3d', ['3d-product', 'perspective', 'floating', 'animated', 'interactive'], 'Centered headline above a 3D-perspective product render that rotates or floats with subtle motion.', ['hero-3d-v1'], 9.1),
  r('hero-waitlist-signup', 'hero', ['startup', 'ai', 'saas'], ['linear', 'notion'], 'centered-form', ['waitlist', 'email-input', 'early-access', 'badge', 'social-proof-count'], 'Early-access hero: badge, headline, subtitle, email input with join button, and "X people already joined" social proof.', ['hero-waitlist-v1'], 9.0),
  r('hero-stats-trust', 'hero', ['enterprise', 'fintech', 'saas'], ['stripe', 'apple'], 'centered-stats', ['stats-row', 'trust-signals', 'logos', 'metric-numbers', 'clean'], 'Centered headline + CTA above a horizontal row of 4 metric stats (companies, users, uptime, NPS).', ['hero-stats-v1'], 9.0),
];

// FEATURES — 9 new (existing: 21 → total: 30)
const newFeatureRefs: SectionRef[] = [
  r('features-icon-grid-6', 'features', ['saas', 'startup', 'ai'], ['linear', 'notion'], 'icon-grid-6col', ['6-column', 'icon-cards', 'flat', 'short-descriptions', 'grid'], '6-column icon + title + 1-line description grid. Best for listing 6–12 capabilities at a glance.', ['features-icon-grid-v1'], 8.5),
  r('features-stats-counters', 'features', ['saas', 'enterprise', 'fintech'], ['stripe', 'vercel'], 'stats-row', ['animated-counters', 'big-numbers', 'metric-highlights', 'plus-suffix'], 'Three or four animated count-up numbers (e.g. 10,000+ customers, 99.9% uptime) with supporting labels.', ['features-counters-v1'], 8.8),
  r('features-side-comparison', 'features', ['saas', 'productivity', 'ecommerce'], ['notion', 'linear'], 'comparison-split', ['before-after', 'side-by-side', 'old-vs-new', 'strikethrough'], 'Two-column before/after comparison: old (crossed out, grey) vs new (highlighted, green). Perfect for migration messaging.', ['features-compare-v1'], 8.9),
  r('features-timeline-horizontal', 'features', ['startup', 'agency', 'saas'], ['framer', 'linear'], 'horizontal-timeline', ['timeline', 'steps', 'numbered', 'progress-dots', 'horizontal-scroll'], 'Horizontal numbered timeline showing 3–5 steps or milestones with connecting lines and icons.', ['features-timeline-v1'], 8.6),
  r('features-tabs-interactive', 'features', ['saas', 'developer', 'analytics'], ['stripe', 'linear'], 'tabbed-feature-showcase', ['tabs', 'interactive', 'product-screenshots', 'switcher', 'active-state'], 'Tabbed feature showcase: click tab (Integration / Analytics / Security) → animated screenshot or UI preview changes.', ['features-tabs-v1'], 9.2),
  r('features-video-demo-v2', 'features', ['saas', 'startup', 'productivity'], ['framer', 'notion'], 'video-embed', ['video', 'product-demo', 'play-button', 'embed', 'loom-style'], 'Centered headline + subtitle with a large video embed (Loom, YouTube, or hosted) showing the product in action.', ['features-video-v2'], 9.0),
  r('features-marquee-logos', 'features', ['saas', 'enterprise', 'startup'], ['vercel', 'linear'], 'infinite-marquee', ['marquee', 'logo-strip', 'infinite-scroll', 'integrations', 'partner-logos'], 'Infinite-scroll marquee of integration/partner logos beneath a "Works with your stack" headline.', ['features-marquee-v1'], 8.4),
  r('features-accordion-expand', 'features', ['saas', 'healthcare', 'legal'], ['notion', 'apple'], 'accordion-list', ['accordion', 'expandable', 'details', 'question-format', 'progressive-disclosure'], 'Left-column accordion list (8–12 items) with expanded detail pane on the right showing screenshot or icon.', ['features-accordion-v1'], 8.7),
  r('features-3-2-1-asymmetric', 'features', ['agency', 'startup', 'ai'], ['framer', 'cursor'], 'asymmetric-3-2-1', ['asymmetric', 'bento', '3-large-2-medium', 'staggered', 'card-mix'], 'Asymmetric bento: row of 3 equal cards, then row of 2 wider cards. Creates visual hierarchy without full bento complexity.', ['features-asym-v1'], 9.1),
];

// PRICING — 15 new (existing: 15 → total: 30)
const newPricingRefs: SectionRef[] = [
  r('pricing-usage-calculator-v2', 'pricing', ['developer', 'ai', 'saas'], ['stripe', 'linear'], 'usage-calculator', ['usage-based', 'pay-as-you-go', 'calculator', 'sliders', 'estimated-cost'], 'Usage-based pricing with interactive slider: "you pay only for what you use." Shows estimated monthly cost.', ['pricing-usage-v2'], 9.1),
  r('pricing-freemium-2col', 'pricing', ['saas', 'startup', 'productivity'], ['notion', 'linear'], 'two-col-freemium', ['free-tier', 'pro-tier', 'two-column', 'feature-list', 'upgrade-cta'], 'Two-column Free / Pro layout. Free column lists limits, Pro column shows unlock benefits. Strong upgrade CTA.', ['pricing-freemium-v1'], 8.9),
  r('pricing-enterprise-table', 'pricing', ['enterprise', 'security', 'analytics'], ['stripe', 'vercel'], 'feature-matrix-table', ['comparison-table', 'feature-matrix', 'check-marks', 'enterprise-row', 'full-comparison'], 'Full feature comparison table: rows = features, columns = plans. Check/X marks. Enterprise row at bottom with "Contact Sales."', ['pricing-table-v1'], 8.8),
  r('pricing-annual-toggle', 'pricing', ['saas', 'startup', 'productivity'], ['linear', 'framer'], 'annual-monthly-toggle', ['toggle-switch', 'monthly-annual', 'save-badge', 'animated-switch', 'discount-percent'], 'Monthly/Annual toggle above pricing cards. Annual selected = green "Save 20%" badge appears. Price animates on switch.', ['pricing-toggle-v1'], 9.2),
  r('pricing-per-seat', 'pricing', ['enterprise', 'saas', 'productivity'], ['stripe', 'notion'], 'per-seat-slider', ['per-seat', 'team-size', 'slider', 'total-price-calc', 'seat-count'], 'Per-seat pricing with "How many seats?" slider that updates the total price in real time.', ['pricing-seat-v1'], 8.7),
  r('pricing-feature-matrix', 'pricing', ['enterprise', 'analytics', 'security'], ['stripe', 'linear'], 'feature-comparison-matrix', ['feature-matrix', 'grouped-rows', 'category-headers', 'sticky-header', 'scroll-table'], 'Comprehensive feature matrix with grouped rows (Performance, Security, Support) and sticky column headers.', ['pricing-matrix-v1'], 8.6),
  r('pricing-startup-single', 'pricing', ['startup', 'saas', 'developer'], ['notion', 'vercel'], 'single-plan', ['single-price', 'all-inclusive', 'simple', 'no-tiers', 'flat-rate'], 'Single all-inclusive price card with feature list and "Everything you need" headline. Used by indie/startup products.', ['pricing-single-v1'], 8.5),
  r('pricing-popular-badge', 'pricing', ['saas', 'startup', 'fintech'], ['stripe', 'framer'], 'three-tier-popular', ['popular-badge', 'highlighted-middle', 'scale-up', 'ring-accent', 'recommended'], 'Three-tier cards with middle card scaled up slightly, ring/shadow accent, and "Most Popular" badge.', ['pricing-popular-v1'], 9.0),
  r('pricing-comparison-competitor', 'pricing', ['saas', 'startup', 'productivity'], ['linear', 'vercel'], 'vs-competitor', ['competitor-comparison', 'vs-table', 'highlight-wins', 'feature-check', 'switch-cta'], 'Side-by-side vs-competitor table: "VoxAI vs Competitor." VoxAI column highlighted green, wins marked with ✓.', ['pricing-vs-v1'], 8.9),
  r('pricing-credit-based', 'pricing', ['ai', 'developer', 'saas'], ['framer', 'cursor'], 'credit-system', ['credits', 'tokens', 'usage-packs', 'buy-more', 'balance'], 'Credit/token-based pricing: buy packs, see what each action costs. "1 build = 100 credits." Progress bar shows balance.', ['pricing-credits-v1'], 8.8),
  r('pricing-success-stories', 'pricing', ['enterprise', 'saas', 'agency'], ['stripe', 'notion'], 'pricing-with-testimonials', ['social-proof', 'testimonials-in-pricing', 'roi-stats', 'customer-quote', 'trust'], 'Pricing cards with a customer quote and ROI stat below each tier. "Customers on Pro save 6hrs/week."', ['pricing-social-v1'], 9.0),
  r('pricing-interactive-calc', 'pricing', ['fintech', 'saas', 'analytics'], ['stripe', 'linear'], 'roi-calculator', ['roi-calculator', 'input-fields', 'savings-output', 'interactive', 'total-value'], 'ROI calculator: input team size, current tool cost → shows "You save $X/year with our platform."', ['pricing-calc-v1'], 9.1),
  r('pricing-discount-banner', 'pricing', ['saas', 'ecommerce', 'startup'], ['framer', 'stripe'], 'discount-header-banner', ['promo-banner', 'limited-time', 'discount-code', 'urgency', 'countdown'], 'Sticky discount banner above pricing: "Limited offer: 30% off all plans this week." Countdown timer.', ['pricing-discount-v1'], 8.4),
  r('pricing-seats-storage', 'pricing', ['saas', 'enterprise', 'productivity'], ['stripe', 'notion'], 'dual-slider', ['seats-storage', 'dual-sliders', 'combined-price', 'interactive', 'team-config'], 'Two interactive sliders (seats + storage GB) that combine to show final monthly price.', ['pricing-dual-slider-v1'], 8.7),
  r('pricing-contact-enterprise', 'pricing', ['enterprise', 'security', 'analytics'], ['stripe', 'vercel'], 'contact-sales-card', ['enterprise-tier', 'contact-sales', 'custom-pricing', 'dedicated-csa', 'sla'], 'Three standard tiers + a fourth Enterprise card with "Contact Sales" CTA, custom pricing, and enterprise features.', ['pricing-enterprise-v1'], 8.8),
];

// TESTIMONIALS — 20 new (existing: 10 → total: 30)
const newTestimonialsRefs: SectionRef[] = [
  r('testimonials-video-grid', 'testimonials', ['saas', 'enterprise', 'startup'], ['stripe', 'framer'], 'video-grid', ['video-testimonials', 'thumbnail-grid', 'play-overlay', 'name-role', 'company'], '2×3 grid of video testimonial thumbnails with play button overlay and customer name/company below.', ['testimonials-video-v1'], 9.2),
  r('testimonials-logo-wall', 'testimonials', ['enterprise', 'saas', 'fintech'], ['vercel', 'linear'], 'logo-wall', ['logo-wall', 'trusted-by', 'grayscale-logos', 'company-logos', 'social-proof'], '"Trusted by 500+ companies" headline above a 5×2 grid of grayscale company logos.', ['testimonials-logos-v1'], 8.8),
  r('testimonials-auto-carousel', 'testimonials', ['saas', 'startup', 'productivity'], ['framer', 'stripe'], 'auto-carousel', ['carousel', 'auto-scroll', 'quote-cards', 'avatar', 'dots-indicator'], 'Auto-scrolling quote carousel with avatar, name, title, and star rating. Dots indicator below.', ['testimonials-carousel-v1'], 8.9),
  r('testimonials-star-grid', 'testimonials', ['saas', 'ecommerce', 'startup'], ['notion', 'linear'], 'star-rating-grid', ['stars', 'rating-grid', 'short-quote', 'avatar', '3×3-grid'], '3×3 grid of cards each showing 5 stars, short quote, avatar, and name. G2/Capterra style.', ['testimonials-stars-v1'], 8.7),
  r('testimonials-twitter-embeds', 'testimonials', ['startup', 'developer', 'ai'], ['linear', 'vercel'], 'twitter-wall', ['twitter', 'tweet-cards', 'social-proof', 'handle', 'verified-badge'], 'Masonry or grid of Twitter/X post cards showing authentic user tweets about the product.', ['testimonials-twitter-v1'], 9.0),
  r('testimonials-case-study-metrics', 'testimonials', ['enterprise', 'saas', 'analytics'], ['stripe', 'notion'], 'case-study-numbers', ['case-study', 'metrics', 'before-after', 'roi', 'outcome-numbers'], 'Case study highlight: company logo + 3 big metric improvements ("↓ 40% support tickets, ↑ 3× revenue").', ['testimonials-case-v1'], 9.3),
  r('testimonials-avatar-mosaic', 'testimonials', ['saas', 'community', 'startup'], ['framer', 'cursor'], 'avatar-mosaic', ['avatar-grid', 'mosaic', 'stacked-photos', 'count-label', 'join-cta'], 'Mosaic of ~20 customer avatar photos with "+2,000 users love this" label and join CTA below.', ['testimonials-mosaic-v1'], 8.6),
  r('testimonials-press-logos', 'testimonials', ['startup', 'saas', 'agency'], ['vercel', 'linear'], 'press-strip', ['press-logos', 'media-mentions', 'featured-in', 'publications', 'news'], '"As featured in" strip: TechCrunch, Forbes, Wired logos in a single horizontal row.', ['testimonials-press-v1'], 8.5),
  r('testimonials-g2-badges', 'testimonials', ['saas', 'enterprise', 'analytics'], ['stripe', 'notion'], 'review-badges', ['g2-badges', 'capterra', 'review-awards', 'season-badges', 'trust-marks'], 'G2 Leader / Capterra Top Rated / ProductHunt badges displayed in a badge row with "4.9/5 from 1,200 reviews."', ['testimonials-badges-v1'], 9.1),
  r('testimonials-founder-spotlight', 'testimonials', ['startup', 'saas', 'agency'], ['notion', 'linear'], 'founder-quote', ['founder-quote', 'large-photo', 'attribution', 'italic', 'single-spotlight'], 'Single large founder/CEO quote with full-width photo background, italic quote text, and name/company attribution.', ['testimonials-founder-v1'], 8.8),
  r('testimonials-partner-certifications', 'testimonials', ['enterprise', 'security', 'fintech'], ['vercel', 'stripe'], 'partner-certs', ['partner-badges', 'certified', 'iso-soc2', 'gdpr', 'compliance-marks'], 'Row of partner/certification logos: AWS Partner, SOC 2, ISO 27001, GDPR Compliant, HIPAA Ready.', ['testimonials-certs-v1'], 8.7),
  r('testimonials-media-quote-strip', 'testimonials', ['startup', 'consumer', 'agency'], ['framer', 'stripe'], 'media-quote-strip', ['media-quotes', 'one-line-quotes', 'source-logo', 'horizontal-strip', 'press'], 'Horizontal strip: "[product] is the future of X" — TechCrunch. Three to five short press quotes in one row.', ['testimonials-media-v1'], 8.9),
  r('testimonials-nps-display', 'testimonials', ['saas', 'startup', 'enterprise'], ['stripe', 'notion'], 'nps-score', ['nps', 'net-promoter', 'score-gauge', 'satisfaction', 'industry-comparison'], 'NPS score widget (gauge or number display) with "72 NPS — top 10% in our industry" label.', ['testimonials-nps-v1'], 8.5),
  r('testimonials-community-count', 'testimonials', ['startup', 'saas', 'community'], ['framer', 'linear'], 'community-stat', ['community-count', 'member-count', 'growing', 'join-us', 'animated-counter'], '"Join 12,000+ professionals" with animated counter and avatar strip + "Join Community" CTA.', ['testimonials-community-v1'], 8.6),
  r('testimonials-employee-reviews', 'testimonials', ['enterprise', 'saas', 'startup'], ['notion', 'vercel'], 'employer-brand', ['employee-reviews', 'glassdoor', 'culture', 'team', 'workplace'], 'Employee review cards (Glassdoor style) for employer branding or team culture sections.', ['testimonials-glassdoor-v1'], 8.2),
  r('testimonials-before-after', 'testimonials', ['saas', 'productivity', 'analytics'], ['stripe', 'framer'], 'before-after-slider', ['before-after', 'slider-reveal', 'before-state', 'after-state', 'transformation'], 'Interactive before/after slider revealing product transformation. "Before: manual, error-prone. After: automated."', ['testimonials-ba-v1'], 9.0),
  r('testimonials-client-roi', 'testimonials', ['enterprise', 'agency', 'fintech'], ['stripe', 'linear'], 'roi-results', ['client-results', 'roi', 'outcome-cards', 'dollar-saved', 'time-saved'], 'Three outcome cards: "Acme saved $120k/year", "Beta reduced churn by 40%", "Gamma deployed 5× faster."', ['testimonials-roi-v1'], 9.2),
  r('testimonials-quote-wall', 'testimonials', ['saas', 'startup', 'community'], ['framer', 'cursor'], 'quote-wall', ['masonry', 'many-quotes', 'variety', 'colorful-cards', 'overflow-fade'], 'Dense masonry wall of 12–20 short quote cards. Fades out at bottom with "See all testimonials" CTA.', ['testimonials-wall-v1'], 8.7),
  r('testimonials-case-study-spotlight', 'testimonials', ['enterprise', 'saas', 'analytics'], ['stripe', 'vercel'], 'case-spotlight', ['full-case-study', 'single-customer', 'logo', 'quote', 'metrics-sidebar', 'read-more'], 'Full-width case study spotlight: customer logo, photo, long quote, metric sidebar, and "Read the full story" CTA.', ['testimonials-spotlight-v1'], 9.1),
  r('testimonials-star-breakdown', 'testimonials', ['ecommerce', 'saas', 'startup'], ['notion', 'stripe'], 'rating-breakdown', ['star-breakdown', '5-4-3-2-1-bars', 'aggregate-score', 'review-count', 'distribution'], 'Aggregate star rating with breakdown bars (5★: 78%, 4★: 15%, ...). Shows review count and average score.', ['testimonials-breakdown-v1'], 8.8),
];

// FAQ — 22 new (existing: 8 → total: 30)
const newFaqRefs: SectionRef[] = [
  r('faq-search-input', 'faq', ['saas', 'enterprise', 'developer'], ['stripe', 'notion'], 'searchable-faq', ['search-input', 'real-time-filter', 'instant-results', 'help-center-style'], 'Searchable FAQ with real-time filter. Type to filter questions instantly. Used in large help centers.', ['faq-search-v1'], 9.0),
  r('faq-category-tabs', 'faq', ['saas', 'ecommerce', 'enterprise'], ['linear', 'stripe'], 'tabbed-faq', ['tabs', 'category-tabs', 'billing-tab', 'security-tab', 'getting-started-tab'], 'Tabbed FAQ: "Getting Started | Pricing | Security | API" tabs, each showing 5–8 relevant questions.', ['faq-tabs-v1'], 8.9),
  r('faq-minimal-numbered', 'faq', ['startup', 'agency', 'portfolio'], ['notion', 'vercel'], 'numbered-list', ['minimal', 'numbered', 'simple', 'no-icons', 'clean-typography'], 'Minimal numbered list of Q&A pairs. No icons, just clean typography and generous spacing.', ['faq-minimal-v1'], 8.4),
  r('faq-support-callout', 'faq', ['saas', 'startup', 'ecommerce'], ['stripe', 'linear'], 'faq-plus-support', ['support-cta', 'chat-link', 'email-link', 'still-questions', 'help'], 'FAQ section ending with "Still have questions? Chat with us or email support@..." callout card.', ['faq-support-v1'], 8.7),
  r('faq-developer-api', 'faq', ['developer', 'saas', 'ai'], ['vercel', 'linear'], 'developer-faq', ['api', 'code-snippets', 'technical', 'rate-limits', 'authentication'], 'Developer-focused FAQ with embedded code snippets and technical details about API, rate limits, auth.', ['faq-dev-v1'], 8.8),
  r('faq-pricing-only', 'faq', ['saas', 'startup', 'fintech'], ['stripe', 'notion'], 'pricing-faq', ['pricing-faq', 'plan-differences', 'upgrade-downgrade', 'refund-policy', 'billing-cycle'], 'Pricing-specific FAQ: "What\'s included in Free?", "Can I upgrade/downgrade?", "What is your refund policy?"', ['faq-pricing-v1'], 8.6),
  r('faq-security-compliance', 'faq', ['enterprise', 'security', 'fintech'], ['stripe', 'vercel'], 'security-faq', ['security', 'compliance', 'soc2', 'data-handling', 'gdpr', 'hipaa'], 'Security and compliance FAQ: data residency, SOC 2, GDPR, HIPAA, encryption, access controls.', ['faq-security-v1'], 8.9),
  r('faq-two-column', 'faq', ['saas', 'enterprise', 'startup'], ['linear', 'framer'], 'two-col-faq', ['two-columns', 'grid', 'side-by-side', 'balanced', 'scannable'], 'Two-column FAQ grid — 4 questions per column. More compact than single-column for pages with 8+ questions.', ['faq-twocol-v1'], 8.5),
  r('faq-expandable-grouped', 'faq', ['saas', 'ecommerce', 'healthcare'], ['stripe', 'notion'], 'grouped-accordion', ['grouped', 'category-headers', 'accordion', 'expandable', 'section-headers'], 'Grouped accordion FAQ with bold category headers (General, Billing, Technical) above each set of questions.', ['faq-grouped-v1'], 8.7),
  r('faq-quick-answers', 'faq', ['startup', 'consumer', 'agency'], ['framer', 'linear'], 'quick-qa', ['short-answers', 'conversational', 'one-liners', '15-questions', 'fast-scan'], 'Quick Q&A format: short questions with 1-2 sentence answers. Great for 10–20 questions that need no elaboration.', ['faq-quick-v1'], 8.3),
  r('faq-troubleshooting', 'faq', ['developer', 'saas', 'enterprise'], ['notion', 'vercel'], 'troubleshooting-guide', ['troubleshooting', 'steps', 'solutions', 'error-codes', 'diagnostic'], 'Troubleshooting guide FAQ with step-by-step resolution paths and error code references.', ['faq-trouble-v1'], 8.5),
  r('faq-getting-started', 'faq', ['saas', 'startup', 'developer'], ['linear', 'stripe'], 'onboarding-faq', ['getting-started', 'setup', 'first-steps', 'quickstart', 'beginner'], '"How do I get started?" section FAQ: account setup, first project, first integration, inviting team.', ['faq-start-v1'], 8.6),
  r('faq-comparison', 'faq', ['saas', 'startup', 'productivity'], ['vercel', 'linear'], 'comparison-faq', ['vs-competitors', 'migration', 'why-us', 'switching', 'difference'], '"How does this compare to X?" FAQ: honest comparison answers covering migration and key differences.', ['faq-compare-v1'], 8.8),
  r('faq-technical', 'faq', ['developer', 'enterprise', 'analytics'], ['stripe', 'vercel'], 'technical-faq', ['technical', 'uptime-sla', 'latency', 'infrastructure', 'webhooks'], 'Technical FAQ: uptime SLA, latency specs, webhook retry logic, infrastructure regions, rate limits.', ['faq-technical-v1'], 8.7),
  r('faq-billing-detailed', 'faq', ['saas', 'enterprise', 'fintech'], ['stripe', 'notion'], 'billing-faq', ['billing', 'invoices', 'payment-methods', 'tax', 'receipts', 'proration'], 'Billing FAQ: payment methods accepted, invoice format, tax handling, proration on upgrades.', ['faq-billing-v1'], 8.5),
  r('faq-integration', 'faq', ['saas', 'developer', 'enterprise'], ['linear', 'stripe'], 'integration-faq', ['integrations', 'webhooks', 'api', 'third-party', 'slack-notion-zapier'], 'Integration FAQ: which tools are supported, how to connect, webhook setup, OAuth flows.', ['faq-integration-v1'], 8.6),
  r('faq-compliance', 'faq', ['enterprise', 'healthcare', 'fintech'], ['stripe', 'vercel'], 'compliance-faq', ['compliance', 'certifications', 'audit-trail', 'data-retention', 'dpa'], 'Compliance FAQ: data retention policy, DPA availability, audit logs, certifications status.', ['faq-compliance-v1'], 8.8),
  r('faq-migration', 'faq', ['saas', 'enterprise', 'developer'], ['notion', 'linear'], 'migration-faq', ['migration', 'import', 'data-transfer', 'switching-cost', 'onboarding-support'], 'Migration FAQ: how to import data, switching cost, migration support team, timeline expectations.', ['faq-migration-v1'], 8.4),
  r('faq-use-cases', 'faq', ['saas', 'enterprise', 'startup'], ['stripe', 'framer'], 'use-cases-faq', ['use-cases', 'who-is-it-for', 'industries', 'team-sizes', 'personas'], '"Who is this for?" FAQ: different use cases by role (founder, marketer, developer), team size, industry.', ['faq-usecase-v1'], 8.7),
  r('faq-glossary', 'faq', ['developer', 'saas', 'enterprise'], ['notion', 'vercel'], 'glossary', ['glossary', 'definitions', 'terminology', 'alphabetical', 'hover-tooltip'], 'Glossary of product terms with letter-indexed navigation. Used in developer and enterprise docs.', ['faq-glossary-v1'], 8.3),
  r('faq-onboarding-steps', 'faq', ['saas', 'startup', 'productivity'], ['linear', 'stripe'], 'step-faq', ['numbered-steps', 'getting-started-guide', 'checklist', 'sequential', 'first-value'], 'Numbered onboarding steps FAQ: "Step 1: Create account → Step 2: Connect your tool → Step 3: Invite team."', ['faq-steps-v1'], 8.5),
  r('faq-policy', 'faq', ['enterprise', 'legal', 'healthcare'], ['notion', 'apple'], 'policy-faq', ['privacy', 'tos', 'cookie-policy', 'data-deletion', 'opt-out'], 'Privacy/policy FAQ: data collection, cookies, deletion requests, opt-out, legal disclosures.', ['faq-policy-v1'], 8.2),
];

// DASHBOARD — 40 new (existing: 10 → total: 50)
const newDashboardRefs: SectionRef[] = [
  r('dashboard-kpi-cards', 'dashboard', ['analytics', 'saas', 'enterprise'], ['stripe', 'linear'], 'kpi-card-row', ['kpi-cards', '4-metrics', 'trend-arrows', 'percentage-change', 'sparklines'], 'Row of 4 KPI metric cards: Total Revenue, Active Users, Churn Rate, MRR. Each with trend arrow and sparkline.', ['dashboard-kpi-v1'], 9.2),
  r('dashboard-chart-grid', 'dashboard', ['analytics', 'saas', 'fintech'], ['stripe', 'vercel'], 'multi-chart', ['line-chart', 'bar-chart', 'donut', 'multi-chart-grid', 'recharts'], '2×2 grid of charts: line chart, bar chart, donut pie, and scatter/area chart. Full analytics overview.', ['dashboard-charts-v1'], 9.0),
  r('dashboard-data-table', 'dashboard', ['enterprise', 'analytics', 'saas'], ['linear', 'notion'], 'data-table', ['sortable-table', 'filters', 'search', 'pagination', 'row-actions'], 'Sortable, filterable data table with search, pagination, and row-level action menus (edit, delete, view).', ['dashboard-table-v1'], 8.9),
  r('dashboard-activity-feed', 'dashboard', ['saas', 'productivity', 'enterprise'], ['notion', 'linear'], 'activity-timeline', ['activity-feed', 'real-time', 'timeline', 'user-actions', 'timestamps'], 'Real-time activity feed: timestamped user actions ("Alice edited Document X — 2 mins ago") with avatar icons.', ['dashboard-activity-v1'], 8.7),
  r('dashboard-notifications', 'dashboard', ['saas', 'enterprise', 'productivity'], ['stripe', 'notion'], 'notification-panel', ['notifications', 'unread-badge', 'mark-all-read', 'notification-types', 'inbox'], 'Notification inbox panel: unread count badge, grouped by type, mark-as-read, and notification settings link.', ['dashboard-notify-v1'], 8.6),
  r('dashboard-user-management', 'dashboard', ['enterprise', 'saas', 'security'], ['stripe', 'vercel'], 'user-table', ['user-management', 'roles', 'permissions', 'invite-button', 'status-badge'], 'User management table: avatar, name, email, role (dropdown), status (active/suspended), last seen, actions.', ['dashboard-users-v1'], 9.1),
  r('dashboard-settings-panel', 'dashboard', ['saas', 'enterprise', 'startup'], ['notion', 'stripe'], 'settings-layout', ['settings', 'sidebar-nav', 'form-sections', 'save-button', 'account-profile'], 'Settings page with left sidebar navigation (Profile, Billing, Team, API, Notifications) and form panels.', ['dashboard-settings-v1'], 8.8),
  r('dashboard-integration-list', 'dashboard', ['saas', 'developer', 'enterprise'], ['linear', 'stripe'], 'integration-cards', ['integrations', 'connected-badge', 'connect-button', 'logos', 'oauth-flow'], 'Integration catalog: logo cards showing connected integrations (green badge) and available ones (Connect button).', ['dashboard-integrations-v1'], 8.9),
  r('dashboard-usage-graph', 'dashboard', ['saas', 'developer', 'analytics'], ['stripe', 'vercel'], 'usage-area-chart', ['usage-graph', 'api-calls', 'area-chart', 'time-range-selector', 'quota-line'], 'Usage graph with date range selector (7d / 30d / 90d), area chart, and quota limit line overlay.', ['dashboard-usage-v1'], 9.0),
  r('dashboard-quota-progress', 'dashboard', ['saas', 'developer', 'startup'], ['linear', 'notion'], 'quota-bars', ['quota-progress', 'usage-bars', 'limit-indicators', 'upgrade-prompt', 'storage-seats'], 'Quota progress bars: Storage (72/100GB), API calls (8,400/10,000), Team seats (8/10). Upgrade prompt at 80%.', ['dashboard-quota-v1'], 8.7),
  r('dashboard-calendar', 'dashboard', ['productivity', 'saas', 'enterprise'], ['notion', 'linear'], 'calendar-grid', ['calendar', 'month-view', 'event-dots', 'click-to-create', 'agenda-sidebar'], 'Calendar view with monthly grid, colored event dots, and agenda sidebar showing today\'s events.', ['dashboard-calendar-v1'], 8.6),
  r('dashboard-kanban', 'dashboard', ['productivity', 'saas', 'startup'], ['linear', 'framer'], 'kanban-board', ['kanban', 'drag-drop', 'columns', 'card-preview', 'status-swimlanes'], 'Kanban board with draggable cards across status columns (To Do → In Progress → Review → Done).', ['dashboard-kanban-v1'], 9.1),
  r('dashboard-pipeline', 'dashboard', ['enterprise', 'saas', 'analytics'], ['stripe', 'linear'], 'sales-pipeline', ['pipeline', 'stages', 'deal-cards', 'revenue-total', 'funnel'], 'Sales pipeline with stage columns (Lead → Qualified → Proposal → Closed) and deal revenue totals per stage.', ['dashboard-pipeline-v1'], 9.0),
  r('dashboard-report-builder', 'dashboard', ['analytics', 'enterprise', 'saas'], ['stripe', 'notion'], 'report-builder', ['report-builder', 'drag-metrics', 'custom-charts', 'export-pdf', 'schedule-email'], 'Custom report builder: drag metrics from sidebar, configure chart type, preview, schedule email delivery.', ['dashboard-reports-v1'], 8.8),
  r('dashboard-team-overview', 'dashboard', ['enterprise', 'saas', 'productivity'], ['notion', 'linear'], 'team-grid', ['team-overview', 'avatar-grid', 'role-badges', 'online-status', 'invite-button'], 'Team member grid: avatar, name, role badge, online/offline indicator, and "Invite Member" card at end.', ['dashboard-team-v1'], 8.7),
  r('dashboard-billing-summary', 'dashboard', ['saas', 'enterprise', 'fintech'], ['stripe', 'vercel'], 'billing-panel', ['billing', 'invoice-list', 'plan-badge', 'next-renewal', 'payment-method'], 'Billing panel: current plan badge, next renewal date, payment method, and invoice history table.', ['dashboard-billing-v1'], 9.0),
  r('dashboard-audit-log', 'dashboard', ['enterprise', 'security', 'saas'], ['stripe', 'notion'], 'audit-log', ['audit-trail', 'event-log', 'user-actions', 'ip-address', 'export-csv'], 'Audit log table: timestamp, user, action, resource, IP address, with CSV export and date filter.', ['dashboard-audit-v1'], 8.8),
  r('dashboard-command-search', 'dashboard', ['saas', 'developer', 'productivity'], ['linear', 'vercel'], 'command-palette', ['command-palette', 'keyboard-shortcut', 'search-everything', 'cmdk', 'recent-items'], 'Command palette (⌘K) with search-everything: recent pages, actions, users, settings, docs links.', ['dashboard-command-v1'], 9.2),
  r('dashboard-onboarding-checklist', 'dashboard', ['saas', 'startup', 'enterprise'], ['notion', 'stripe'], 'setup-checklist', ['onboarding', 'checklist', 'progress-bar', 'steps', 'completion-reward'], 'Onboarding checklist card: "Complete your setup (3/6 steps)" with progress bar and checkmark items.', ['dashboard-onboard-v1'], 8.9),
  r('dashboard-map-view', 'dashboard', ['analytics', 'enterprise', 'ecommerce'], ['stripe', 'vercel'], 'geo-map', ['map', 'geographic', 'choropleth', 'heat-map', 'country-breakdown'], 'Geographic map visualization showing user/revenue distribution by country with hover tooltips.', ['dashboard-map-v1'], 8.5),
  // V7.2.7 — 20 additional specialized dashboard refs
  r('dashboard-devops-pipeline', 'dashboard', ['developer', 'enterprise', 'saas'], ['vercel', 'linear'], 'ci-cd-status', ['ci-cd', 'deployments', 'pipeline-status', 'build-log', 'github-actions'], 'CI/CD pipeline status: branch badges, build stages (lint→test→deploy), duration, success/failure badges.', ['dashboard-devops-v1'], 9.1),
  r('dashboard-hr-overview', 'dashboard', ['enterprise', 'saas', 'startup'], ['notion', 'stripe'], 'hr-dashboard', ['headcount', 'hiring-pipeline', 'time-off', 'org-chart', 'attrition'], 'HR dashboard: headcount KPIs, open roles funnel, PTO requests table with approval badges, attrition rate.', ['dashboard-hr-v1'], 8.7),
  r('dashboard-support-tickets', 'dashboard', ['saas', 'enterprise', 'startup'], ['linear', 'stripe'], 'helpdesk-queue', ['tickets', 'priority-badge', 'sla-timer', 'assignee', 'resolution-time'], 'Support ticket queue: priority badges (P0–P3), SLA countdown, assignee avatar, status (open/in-progress/resolved).', ['dashboard-tickets-v1'], 9.0),
  r('dashboard-project-tracker', 'dashboard', ['saas', 'productivity', 'enterprise'], ['linear', 'notion'], 'project-milestones', ['milestones', 'gantt', 'assignees', 'due-dates', 'progress-rings'], 'Project tracker: milestone rows with progress bars, assignee avatars, due dates, status badges (on-track/at-risk/done).', ['dashboard-projects-v1'], 8.9),
  r('dashboard-ecommerce-orders', 'dashboard', ['ecommerce', 'saas', 'startup'], ['stripe', 'vercel'], 'order-management', ['orders', 'fulfillment', 'sku', 'shipping-status', 'revenue-today'], 'Order management table: order ID, customer, SKU, amount, fulfillment status badge (shipped/pending/cancelled).', ['dashboard-orders-v1'], 9.0),
  r('dashboard-api-explorer', 'dashboard', ['developer', 'saas', 'enterprise'], ['vercel', 'stripe'], 'api-request-log', ['api-logs', 'endpoint-list', 'latency', 'error-rate', 'request-inspector'], 'API explorer: endpoint list with request count, avg latency, error rate badge, expandable request/response inspector.', ['dashboard-api-v1'], 8.8),
  r('dashboard-asset-library', 'dashboard', ['saas', 'agency', 'enterprise'], ['notion', 'framer'], 'media-library', ['asset-grid', 'file-management', 'upload', 'filter-type', 'preview-modal'], 'Asset/media library grid: file type filter tabs, search, thumbnail grid, file size badge, download/copy link actions.', ['dashboard-assets-v1'], 8.6),
  r('dashboard-role-permissions', 'dashboard', ['enterprise', 'saas', 'security'], ['linear', 'stripe'], 'rbac-matrix', ['rbac', 'permission-matrix', 'toggle-switches', 'role-columns', 'resource-rows'], 'RBAC permission matrix: resource rows × role columns, toggle switches per cell, save-changes button, audit tooltip.', ['dashboard-permissions-v1'], 8.9),
  r('dashboard-health-monitoring', 'dashboard', ['developer', 'enterprise', 'saas'], ['vercel', 'stripe'], 'uptime-monitor', ['uptime', 'service-health', 'incident-log', 'p95-latency', 'status-badges'], 'Health monitoring: uptime % badges per service, p95 latency sparkline, incident log table with severity badges.', ['dashboard-health-v1'], 9.1),
  r('dashboard-customer-success', 'dashboard', ['saas', 'enterprise', 'startup'], ['stripe', 'notion'], 'cs-dashboard', ['health-score', 'churn-risk', 'nps-trend', 'renewal-date', 'account-manager'], 'Customer success: health score gauge per account, churn risk badge (low/med/high), NPS trend, renewal date, ARR.', ['dashboard-cs-v1'], 9.0),
  r('dashboard-content-calendar', 'dashboard', ['saas', 'media', 'agency'], ['notion', 'framer'], 'editorial-calendar', ['content-schedule', 'publish-status', 'channel-badge', 'review-queue', 'monthly-grid'], 'Content calendar: monthly grid with post cards, channel badges (Twitter/LinkedIn/Blog), status (draft/scheduled/live).', ['dashboard-content-v1'], 8.7),
  r('dashboard-email-analytics', 'dashboard', ['saas', 'marketing', 'startup'], ['stripe', 'notion'], 'campaign-analytics', ['open-rate', 'click-rate', 'campaign-table', 'ab-test-badge', 'unsubscribe'], 'Email analytics: campaign table with open rate, CTR, unsubscribes, A/B test winner badge, send volume sparkline.', ['dashboard-email-v1'], 8.8),
  r('dashboard-lead-scoring', 'dashboard', ['saas', 'enterprise', 'startup'], ['stripe', 'linear'], 'lead-score-table', ['lead-score', 'activity-feed', 'conversion-funnel', 'fit-badge', 'intent-signals'], 'Lead scoring table: score badge, company fit (strong/weak), intent signals, last activity, stage dropdown.', ['dashboard-leads-v1'], 9.0),
  r('dashboard-compliance-tracker', 'dashboard', ['enterprise', 'healthcare', 'fintech'], ['stripe', 'notion'], 'compliance-checklist', ['soc2', 'gdpr', 'hipaa', 'audit-status', 'requirement-badge'], 'Compliance tracker: requirement rows with status badges (certified/in-progress/gap), owner, due date, evidence link.', ['dashboard-compliance-v1'], 8.9),
  r('dashboard-multi-tenancy', 'dashboard', ['enterprise', 'saas', 'developer'], ['stripe', 'vercel'], 'tenant-overview', ['multi-tenant', 'plan-badge', 'usage-per-tenant', 'provisioning', 'sla-tier'], 'Multi-tenant overview: tenant rows with plan badge, MAU, storage used, API calls, SLA tier, provision date.', ['dashboard-tenancy-v1'], 8.8),
  r('dashboard-feature-flags', 'dashboard', ['developer', 'saas', 'startup'], ['linear', 'vercel'], 'feature-toggles', ['feature-flags', 'rollout-percentage', 'targeting-rules', 'toggle-switch', 'variants'], 'Feature flag dashboard: flag list with toggle switches, rollout % slider, targeting rules (by segment/user), variants.', ['dashboard-flags-v1'], 9.0),
  r('dashboard-inventory', 'dashboard', ['ecommerce', 'enterprise', 'saas'], ['stripe', 'notion'], 'inventory-table', ['stock-levels', 'low-stock-badge', 'reorder-point', 'sku-table', 'supplier'], 'Inventory management: SKU table with stock level badge (in-stock/low/out), reorder point alert, supplier column.', ['dashboard-inventory-v1'], 8.7),
  r('dashboard-workspace-home', 'dashboard', ['saas', 'productivity', 'enterprise'], ['notion', 'linear'], 'workspace-home', ['pinned-docs', 'recent-activity', 'quick-actions', 'team-updates', 'welcome-card'], 'Workspace home: welcome card with user name, pinned documents grid, recent activity feed, quick action buttons.', ['dashboard-workspace-v1'], 8.9),
  r('dashboard-release-management', 'dashboard', ['developer', 'saas', 'enterprise'], ['linear', 'vercel'], 'changelog-releases', ['releases', 'changelog', 'version-history', 'semver-badge', 'rollback-button'], 'Release management: version rows with semver badge (major/minor/patch), release notes preview, rollback action.', ['dashboard-releases-v1'], 8.8),
  r('dashboard-user-growth', 'dashboard', ['analytics', 'saas', 'startup'], ['stripe', 'vercel'], 'growth-metrics', ['dau-mau', 'cohort-chart', 'signup-source', 'activation-rate', 'retention-curve'], 'User growth dashboard: DAU/MAU cards, cohort retention table, signup source pie, activation rate funnel.', ['dashboard-growth-v1'], 9.1),
];

// CTA — 22 new (existing: 8 → total: 30)
const newCtaRefs: SectionRef[] = [
  r('cta-newsletter-inline', 'cta', ['saas', 'media', 'startup'], ['notion', 'linear'], 'inline-newsletter', ['newsletter', 'email-input', 'inline-form', 'subscribe', 'privacy-note'], 'Inline newsletter CTA: "Stay ahead of the curve." Email input + Subscribe button. Small privacy note below.', ['cta-newsletter-v1'], 8.7),
  r('cta-floating-bottom-bar', 'cta', ['saas', 'ecommerce', 'startup'], ['framer', 'stripe'], 'floating-bar', ['floating-bar', 'sticky-bottom', 'dismiss-x', 'urgent', 'persistent'], 'Sticky bottom floating bar: "Free trial ends in 3 days — Upgrade now." Dismiss X button. High visibility.', ['cta-floating-v1'], 8.8),
  r('cta-sticky-header', 'cta', ['saas', 'enterprise', 'startup'], ['linear', 'vercel'], 'sticky-header-cta', ['sticky-nav', 'cta-in-header', 'scroll-triggered', 'compact', 'persistent-cta'], 'Sticky header CTA that appears after user scrolls past hero. Compact "Start Free Trial" button in nav bar.', ['cta-sticky-v1'], 8.9),
  r('cta-split-two-col', 'cta', ['saas', 'enterprise', 'startup'], ['stripe', 'notion'], 'split-cta', ['two-column', 'left-headline', 'right-form', 'split-layout', 'prominent'], 'Split CTA: left column with bold headline + benefits list, right column with email input or demo booking form.', ['cta-split-v1'], 9.1),
  r('cta-countdown-urgency', 'cta', ['saas', 'ecommerce', 'startup'], ['framer', 'stripe'], 'countdown-cta', ['countdown-timer', 'urgency', 'limited-offer', 'days-hours-mins', 'scarcity'], 'Countdown timer CTA: "Offer expires in 2d 14h 32m." Countdown clock above a primary CTA button.', ['cta-countdown-v1'], 8.6),
  r('cta-social-proof-quote', 'cta', ['saas', 'enterprise', 'startup'], ['stripe', 'framer'], 'cta-with-quote', ['social-proof', 'quote', 'avatar', 'before-button', 'trust-boost'], 'CTA with embedded testimonial quote above the button: "We saved 10hrs/week." — John D., CEO. Then CTA.', ['cta-social-v1'], 9.0),
  r('cta-waitlist-form', 'cta', ['startup', 'ai', 'saas'], ['linear', 'framer'], 'waitlist-cta', ['waitlist', 'position-counter', 'email-collect', 'early-access-badge', 'referral'], 'Waitlist CTA: "Join the waitlist — 1,240 people ahead of you." Email input, position counter, referral link.', ['cta-waitlist-v1'], 9.0),
  r('cta-early-access-badge', 'cta', ['startup', 'ai', 'developer'], ['cursor', 'framer'], 'early-access-cta', ['early-access', 'badge', 'limited-spots', 'invite-only', 'exclusive'], 'Early Access CTA: pulsing badge "Early Access", headline "Be among the first 100 users", email form.', ['cta-early-v1'], 8.9),
  r('cta-free-trial-input', 'cta', ['saas', 'startup', 'productivity'], ['stripe', 'linear'], 'free-trial-inline', ['free-trial', 'inline-input', 'no-cc', 'start-button', 'trust-line'], 'Free trial CTA: "Start your 14-day free trial." Email input inline + Start button. "No credit card required."', ['cta-trial-v1'], 9.2),
  r('cta-demo-booking', 'cta', ['enterprise', 'saas', 'analytics'], ['stripe', 'notion'], 'demo-booking-cta', ['demo', 'calendly', 'book-a-call', 'schedule', '30-min-call'], '"See it in action" CTA with embedded Calendly-style booking widget or "Book a 30-min demo" button.', ['cta-demo-v1'], 9.0),
  r('cta-live-chat', 'cta', ['ecommerce', 'saas', 'startup'], ['framer', 'notion'], 'live-chat-cta', ['chat-bubble', 'support-cta', 'talk-to-us', 'intercom-style', 'instant-help'], 'Live chat CTA section: "Have questions? Chat with our team." + chat button that opens support widget.', ['cta-chat-v1'], 8.5),
  r('cta-referral-program', 'cta', ['saas', 'startup', 'ecommerce'], ['framer', 'linear'], 'referral-cta', ['referral', 'invite-friends', 'earn-rewards', 'share-link', 'points'], 'Referral program CTA: "Invite friends, earn rewards." Share link generator + reward breakdown.', ['cta-referral-v1'], 8.7),
  r('cta-upgrade-prompt', 'cta', ['saas', 'startup', 'enterprise'], ['stripe', 'linear'], 'upgrade-cta', ['upgrade', 'feature-locked', 'lock-icon', 'plan-benefits', 'in-app'], 'In-app upgrade prompt: locked feature blur + "Unlock with Pro" CTA + 3 upgrade benefits listed.', ['cta-upgrade-v1'], 8.8),
  r('cta-success-state', 'cta', ['saas', 'startup', 'ecommerce'], ['framer', 'notion'], 'success-cta', ['success', 'confirmation', 'checkmark', 'next-steps', 'celebration'], 'Post-signup/purchase success state CTA: checkmark animation, "You\'re all set!" headline, next steps cards.', ['cta-success-v1'], 8.6),
  r('cta-personalized-use-case', 'cta', ['saas', 'enterprise', 'startup'], ['stripe', 'notion'], 'use-case-selector', ['personalized', 'role-selector', 'developer-or-marketer', 'segmented', 'dynamic'], 'Use-case selector CTA: "I am a [Developer / Marketer / Designer]" — clicking adapts button text and destination.', ['cta-personal-v1'], 9.1),
  r('cta-milestone-celebration', 'cta', ['saas', 'startup', 'community'], ['framer', 'cursor'], 'milestone-cta', ['milestone', 'celebration', 'confetti', 'community-count', 'social-momentum'], '"10,000 users — celebrate with us" CTA with confetti animation and community stats.', ['cta-milestone-v1'], 8.7),
  r('cta-vs-comparison', 'cta', ['saas', 'startup', 'productivity'], ['linear', 'vercel'], 'comparison-cta', ['switch-from', 'vs-competitor', 'migration-cta', 'comparison-link', 'better-choice'], '"Switching from Competitor?" CTA with comparison link and migration support offer.', ['cta-compare-v1'], 8.8),
  r('cta-case-study-read', 'cta', ['enterprise', 'saas', 'agency'], ['stripe', 'notion'], 'read-case-study-cta', ['case-study-link', 'customer-logo', 'outcome-teaser', 'read-story', 'trust'], 'Read case study CTA: customer logo + one-line outcome teaser + "Read the full story →" link.', ['cta-casestudy-v1'], 8.9),
  r('cta-announcement-bar', 'cta', ['saas', 'startup', 'ecommerce'], ['linear', 'framer'], 'announcement-bar', ['top-bar', 'announcement', 'new-feature', 'learn-more', 'dismissible'], 'Top-of-page announcement bar: "🚀 New: AI section generation is live — Learn more →" Yellow/brand color.', ['cta-announce-v1'], 8.5),
  r('cta-app-download', 'cta', ['consumer', 'health', 'startup'], ['apple', 'framer'], 'app-store-cta', ['app-store', 'google-play', 'qr-code', 'download-buttons', 'mobile-mockup'], 'App download CTA: App Store + Google Play badges + phone mockup + optional QR code.', ['cta-appstore-v1'], 8.8),
  r('cta-community-join', 'cta', ['startup', 'developer', 'saas'], ['linear', 'framer'], 'community-cta', ['slack-community', 'discord', 'join-group', 'member-count', 'free'], '"Join our community" CTA: Discord/Slack logo, member count, free badge, "Join 5,000+ members" button.', ['cta-community-v1'], 8.7),
  r('cta-event-conference', 'cta', ['enterprise', 'saas', 'agency'], ['framer', 'stripe'], 'event-cta', ['conference', 'webinar', 'register', 'date-time', 'limited-seats'], 'Event/webinar CTA: date, time, "Limited seats" badge, speaker avatars, Register button.', ['cta-event-v1'], 8.6),
];

// NAVBAR — 22 new (existing: 8 → total: 30)
const newNavbarRefs: SectionRef[] = [
  r('navbar-mega-dropdown-v2', 'navbar', ['enterprise', 'saas', 'ecommerce'], ['stripe', 'linear'], 'mega-dropdown', ['mega-menu', 'dropdown', 'multi-column', 'featured-section', 'product-categories'], 'Mega menu dropdown: multi-column grid of links with featured section, icons, and brief descriptions.', ['navbar-mega-v2'], 9.0),
  r('navbar-dark-glass', 'navbar', ['ai', 'startup', 'gaming'], ['cursor', 'framer'], 'dark-glass', ['dark', 'transparent', 'blur-backdrop', 'glass', 'border-bottom'], 'Dark glassmorphism navbar: blurred translucent background, light logo, ghost nav links, outline CTA.', ['navbar-glass-v1'], 8.9),
  r('navbar-sticky-hide-scroll', 'navbar', ['saas', 'agency', 'startup'], ['framer', 'linear'], 'smart-sticky', ['hide-on-scroll-down', 'show-on-scroll-up', 'smart-sticky', 'compact', 'smooth-transition'], 'Smart sticky navbar: hides when user scrolls down (conserves reading space), reappears on scroll up.', ['navbar-sticky-v1'], 8.7),
  r('navbar-minimal-logo-cta', 'navbar', ['startup', 'portfolio', 'agency'], ['notion', 'vercel'], 'minimal-logo-cta', ['minimal', 'logo-only', 'single-cta', 'no-links', 'clean'], 'Ultra-minimal: just logo on left + single CTA button on right. Used on focused landing pages.', ['navbar-minimal-v1'], 8.5),
  r('navbar-with-search', 'navbar', ['developer', 'saas', 'ecommerce'], ['stripe', 'notion'], 'search-bar', ['search-input', 'global-search', 'keyboard-shortcut', '⌘K', 'docs-search'], 'Navbar with search bar (or ⌘K trigger) for docs, products, or enterprise apps with many pages.', ['navbar-search-v1'], 8.8),
  r('navbar-announcement-strip', 'navbar', ['saas', 'ecommerce', 'startup'], ['framer', 'stripe'], 'above-nav-strip', ['announcement-strip', 'above-navbar', 'promo-bar', 'dismissible', 'colored-bar'], 'Thin announcement bar above the main navbar: "New: Feature X is live →" with dismiss button.', ['navbar-strip-v1'], 8.6),
  r('navbar-user-avatar', 'navbar', ['saas', 'enterprise', 'productivity'], ['stripe', 'notion'], 'authenticated-nav', ['user-menu', 'avatar-dropdown', 'signed-in', 'profile-link', 'logout'], 'Authenticated user navbar: logo + links + right-side avatar with dropdown (Profile, Settings, Logout).', ['navbar-user-v1'], 8.9),
  r('navbar-pricing-link', 'navbar', ['saas', 'startup', 'enterprise'], ['linear', 'stripe'], 'pricing-prominent', ['pricing-link', 'highlighted', 'conversion-focused', 'bold-pricing', 'nav-cta'], 'Marketing navbar with Pricing link styled boldly (different color or underline) to drive upgrade conversions.', ['navbar-pricing-v1'], 8.7),
  r('navbar-github-stars', 'navbar', ['developer', 'saas', 'startup'], ['vercel', 'linear'], 'github-badge', ['github-stars', 'star-count', 'social-proof', 'developer-cred', 'badge'], 'Developer navbar with GitHub star count badge (e.g. "★ 4.2k") linking to the repo.', ['navbar-github-v1'], 8.8),
  r('navbar-product-hunt', 'navbar', ['startup', 'saas', 'consumer'], ['framer', 'linear'], 'ph-badge', ['product-hunt', 'ph-badge', 'daily-rank', '#1-product', 'launch-day'], 'Product Hunt "Product of the Day #1" badge in the navbar. Used during and after PH launches.', ['navbar-ph-v1'], 8.5),
  r('navbar-language-switcher', 'navbar', ['enterprise', 'ecommerce', 'saas'], ['notion', 'stripe'], 'i18n-switcher', ['language', 'locale-selector', 'globe-icon', 'dropdown-languages', 'i18n'], 'Language/locale switcher in navbar: globe icon → dropdown of languages (EN, FR, DE, ES, JP).', ['navbar-i18n-v1'], 8.3),
  r('navbar-docs-sidebar', 'navbar', ['developer', 'saas', 'enterprise'], ['vercel', 'notion'], 'docs-nav', ['docs', 'sidebar-navigation', 'collapsible-sections', 'active-page', 'breadcrumbs'], 'Documentation sidebar navigation with collapsible sections, active page highlight, and search.', ['navbar-docs-v1'], 9.0),
  r('navbar-marketing-app-toggle', 'navbar', ['saas', 'startup', 'enterprise'], ['linear', 'stripe'], 'dual-mode-nav', ['marketing-app-switch', 'go-to-dashboard', 'dual-nav', 'marketing-and-app'], 'Navbar that switches between marketing site (Home, Pricing, Blog) and app dashboard (⌘K, notifications, user menu).', ['navbar-toggle-v1'], 8.9),
  r('navbar-notification-bell', 'navbar', ['saas', 'enterprise', 'productivity'], ['stripe', 'notion'], 'notification-nav', ['notification-bell', 'unread-count', 'badge', 'inbox-dropdown', 'alert-icon'], 'App navbar with notification bell icon, unread count badge, and dropdown notification preview.', ['navbar-bell-v1'], 8.6),
  r('navbar-progress-steps', 'navbar', ['saas', 'startup', 'enterprise'], ['stripe', 'framer'], 'step-indicator-nav', ['progress-steps', 'onboarding-steps', 'step-1-2-3', 'completion-bar', 'wizard-nav'], 'Wizard/onboarding step indicator in the navbar: "1 → 2 → 3" with current step highlighted.', ['navbar-steps-v1'], 8.7),
  r('navbar-tabbed', 'navbar', ['saas', 'analytics', 'enterprise'], ['linear', 'notion'], 'tab-navigation', ['tabs', 'section-tabs', 'underline-active', 'page-sections', 'anchor-links'], 'Tabbed section navigation bar: tabs scroll the page to corresponding sections (Overview / Features / Pricing).', ['navbar-tabs-v1'], 8.5),
  r('navbar-side-rail', 'navbar', ['saas', 'enterprise', 'analytics'], ['stripe', 'notion'], 'left-sidebar', ['side-nav', 'left-rail', 'icon-and-label', 'collapsible', 'app-navigation'], 'Left sidebar navigation rail with icons + labels for app sections. Collapses to icon-only on narrower screens.', ['navbar-side-v1'], 9.1),
  r('navbar-command-palette-trigger', 'navbar', ['developer', 'saas', 'productivity'], ['linear', 'vercel'], 'cmd-nav', ['⌘K', 'command-palette', 'quick-nav', 'keyboard-first', 'search-nav'], 'Navbar with prominent ⌘K command palette button. Keyboard-first navigation for power users.', ['navbar-cmd-v1'], 9.0),
  r('navbar-mobile-sheet', 'navbar', ['saas', 'startup', 'ecommerce'], ['framer', 'linear'], 'mobile-sheet', ['hamburger', 'slide-out-sheet', 'full-height', 'mobile', 'overlay-menu'], 'Mobile hamburger → full-height slide-out sheet with all nav links, CTAs, and social links.', ['navbar-mobile-v1'], 8.8),
  r('navbar-breadcrumb', 'navbar', ['developer', 'enterprise', 'ecommerce'], ['notion', 'vercel'], 'breadcrumb-trail', ['breadcrumb', 'path', 'home-chevron', 'category-page', 'nested'], 'Breadcrumb trail for deep navigation: Home > Category > Sub-category > Current Page.', ['navbar-breadcrumb-v1'], 8.4),
  r('navbar-with-status', 'navbar', ['saas', 'enterprise', 'developer'], ['stripe', 'linear'], 'status-indicator', ['system-status', 'uptime-dot', 'operational', 'incident-badge', 'status-page'], 'Navbar with system status indicator: green dot "All Systems Operational" or red "Incident ongoing."', ['navbar-status-v1'], 8.6),
  r('navbar-product-menu', 'navbar', ['saas', 'enterprise', 'startup'], ['stripe', 'framer'], 'product-nav-menu', ['products-dropdown', 'product-logos', 'sub-products', 'suite', 'family'], 'Products dropdown menu: logos and descriptions for each product in a suite (e.g., Analytics, Billing, Support).', ['navbar-products-v1'], 8.9),
];

// FOOTER — 20 NEW (entirely new section type)
const newFooterRefs: SectionRef[] = [
  r('footer-link-columns', 'footer', ['saas', 'enterprise', 'startup'], ['stripe', 'linear'], 'multi-column-links', ['link-columns', 'product-company-legal', 'newsletter', '5-columns', 'organized'], 'Classic multi-column footer: Product / Company / Resources / Legal columns + newsletter input on right.', ['footer-columns-v1'], 9.0),
  r('footer-newsletter-signup', 'footer', ['saas', 'media', 'startup'], ['notion', 'framer'], 'newsletter-footer', ['newsletter', 'email-input', 'subscribe', 'privacy-note', 'compact'], 'Newsletter-first footer: large "Stay in the loop" headline, email input + subscribe, then minimal links below.', ['footer-newsletter-v1'], 8.8),
  r('footer-minimal-copyright', 'footer', ['startup', 'portfolio', 'agency'], ['notion', 'vercel'], 'minimal-footer', ['minimal', 'logo-copyright', 'social-icons', 'one-row', 'clean'], 'Minimal one-row footer: logo left, copyright center, social icons right. Nothing else.', ['footer-minimal-v1'], 8.5),
  r('footer-dark-gradient', 'footer', ['ai', 'startup', 'gaming'], ['cursor', 'framer'], 'dark-gradient-footer', ['dark', 'gradient-top', 'glow', 'logo-large', 'dark-theme'], 'Dark footer with gradient fade-in from page. Large centered logo, minimal links, social icons.', ['footer-dark-v1'], 9.1),
  r('footer-social-links', 'footer', ['startup', 'consumer', 'media'], ['framer', 'linear'], 'social-footer', ['social-icons', 'twitter-github', 'linkedin', 'community-links', 'connect'], 'Social-focused footer: "Find us everywhere" headline + large social platform icons + community links.', ['footer-social-v1'], 8.7),
  r('footer-certifications', 'footer', ['enterprise', 'security', 'fintech'], ['stripe', 'vercel'], 'cert-footer', ['certifications', 'soc2', 'iso', 'hipaa-gdpr', 'trust-marks', 'compliance'], 'Compliance-first footer: SOC 2, ISO 27001, GDPR, HIPAA certification badges above standard link columns.', ['footer-certs-v1'], 8.9),
  r('footer-sitemap', 'footer', ['enterprise', 'saas', 'ecommerce'], ['notion', 'stripe'], 'sitemap-footer', ['sitemap', 'many-links', '6-columns', 'comprehensive', 'seo-links'], 'Comprehensive sitemap footer with 6+ columns covering all product pages, use cases, and industries.', ['footer-sitemap-v1'], 8.4),
  r('footer-legal', 'footer', ['legal', 'enterprise', 'healthcare'], ['apple', 'notion'], 'legal-footer', ['legal', 'privacy-policy', 'terms', 'cookie-settings', 'disclaimer', 'minimal'], 'Legal-focused footer: Privacy Policy, Terms of Service, Cookie Settings, Accessibility links. Minimal design.', ['footer-legal-v1'], 8.3),
  r('footer-multilingual', 'footer', ['enterprise', 'ecommerce', 'saas'], ['stripe', 'notion'], 'locale-footer', ['language-selector', 'region', 'currency', 'globe-icon', 'locale-switcher'], 'Multilingual footer with language/region selector (globe icon + dropdown) and currency switcher.', ['footer-i18n-v1'], 8.5),
  r('footer-product-changelog', 'footer', ['saas', 'developer', 'startup'], ['linear', 'vercel'], 'product-footer', ['changelog', 'product-links', 'status-link', 'version', 'roadmap'], 'Product footer: links to Changelog, Roadmap, Status page, API Docs, and GitHub alongside standard links.', ['footer-product-v1'], 8.8),
  r('footer-support', 'footer', ['saas', 'enterprise', 'ecommerce'], ['stripe', 'notion'], 'support-footer', ['support-links', 'help-center', 'contact', 'community', 'onboarding-guide'], 'Support-first footer: Help Center, Contact Support, Community, and Onboarding Guide prominently featured.', ['footer-support-v1'], 8.6),
  r('footer-startup-simple', 'footer', ['startup', 'saas', 'developer'], ['linear', 'framer'], 'startup-footer', ['startup', 'simple', 'logo-tagline', 'few-links', 'twitter'], 'Startup simple: logo + 1-line tagline, 4–5 essential links, Twitter icon. No bloat.', ['footer-startup-v1'], 8.7),
  r('footer-enterprise-offices', 'footer', ['enterprise', 'saas', 'fintech'], ['stripe', 'vercel'], 'enterprise-footer', ['office-locations', 'global', 'address', 'contact-form-link', 'hq'], 'Enterprise footer: global office addresses listed (San Francisco, London, Singapore) with contact form link.', ['footer-enterprise-v1'], 8.6),
  r('footer-creative-agency', 'footer', ['agency', 'media', 'startup'], ['framer', 'cursor'], 'creative-footer', ['creative', 'big-cta', 'lets-work-together', 'email-link', 'award-badges'], '"Let\'s work together." Creative agency footer with large headline, email link, and award badge strip.', ['footer-creative-v1'], 9.0),
  r('footer-developer-docs', 'footer', ['developer', 'saas', 'enterprise'], ['vercel', 'linear'], 'dev-footer', ['docs-links', 'api-reference', 'github', 'npm', 'changelog', 'cli'], 'Developer footer: API Docs, GitHub, npm package, CLI reference, Changelog, Community Discord.', ['footer-dev-v1'], 8.9),
  r('footer-app-stores', 'footer', ['consumer', 'health', 'startup'], ['apple', 'framer'], 'app-store-footer', ['app-store', 'google-play', 'download-badges', 'rating', 'mobile-app'], 'App download footer: App Store + Google Play badges with star ratings below standard link columns.', ['footer-app-v1'], 8.7),
  r('footer-ecommerce', 'footer', ['ecommerce', 'consumer', 'startup'], ['stripe', 'apple'], 'ecommerce-footer', ['shipping', 'returns', 'size-guide', 'trust-logos', 'payment-badges'], 'Ecommerce footer: shipping policy, returns, size guide links + trust logos (Visa, Mastercard, PayPal, SSL).', ['footer-ecom-v1'], 8.8),
  r('footer-saas-detailed', 'footer', ['saas', 'enterprise', 'startup'], ['stripe', 'linear'], 'saas-footer', ['detailed', 'product-resources-company', 'social', 'newsletter', 'status-badge'], 'Comprehensive SaaS footer with Product / Resources / Company / Legal columns, newsletter, social, and status badge.', ['footer-saas-v1'], 9.1),
  r('footer-agency-credits', 'footer', ['agency', 'startup', 'portfolio'], ['framer', 'notion'], 'agency-credits', ['designed-by', 'built-by', 'credits', 'portfolio-link', 'attribution'], 'Agency portfolio footer with "Designed & Built by Studio X" credit, year, and tools attribution.', ['footer-agency-v1'], 8.4),
  r('footer-healthcare', 'footer', ['healthcare', 'legal', 'enterprise'], ['apple', 'notion'], 'healthcare-footer', ['hipaa', 'medical-disclaimer', 'not-medical-advice', 'accessibility', 'ada-compliance'], 'Healthcare footer: HIPAA badge, medical disclaimer text, accessibility statement, ADA compliance notice.', ['footer-health-v1'], 8.8),
];

// ── Combined SECTION_CORPUS ───────────────────────────────────────────────────
// Cast existing DesignReference[] → SectionRef[] (all have valid SectionType categories)
const existingAsSectionRefs = DESIGN_CORPUS as unknown as SectionRef[];

const ALL_NEW_REFS: SectionRef[] = [
  ...newHeroRefs,
  ...newFeatureRefs,
  ...newPricingRefs,
  ...newTestimonialsRefs,
  ...newFaqRefs,
  ...newDashboardRefs,
  ...newCtaRefs,
  ...newNavbarRefs,
  ...newFooterRefs,
];

export const SECTION_CORPUS: SectionRef[] = [
  ...existingAsSectionRefs,
  ...ALL_NEW_REFS,
];

// ── Section Index: grouped for O(1) section lookup ────────────────────────────
export const SECTION_INDEX: Record<SectionType, SectionRef[]> = {} as Record<SectionType, SectionRef[]>;

for (const type of ALL_SECTION_TYPES) {
  SECTION_INDEX[type] = SECTION_CORPUS.filter(r => r.category === type);
}
