// ── V7.3.2 Component Catalog ──────────────────────────────────────────────────
// Registry of every reusable component with DNA/industry/auth metadata.
// Used by treeBuilder to select the right components per section.

import type { SectionType, DNABrand, Industry, AuthState } from "./componentTreeTypes.js";

export interface CatalogEntry {
  id: string;
  name: string;
  sectionType: SectionType;
  supportedDNAs: DNABrand[];
  supportedIndustries: Industry[];
  supportedAuthStates: AuthState[];
  recommendedShadcn: string[];
  complexity: 'simple' | 'medium' | 'complex';
  dependencies: string[];
  requiresTrustSignal: boolean;
  requiresCTA: boolean;
  priority: number;
}

const ALL_DNAS: DNABrand[] = ['stripe', 'linear', 'vercel', 'notion', 'framer', 'cursor', 'perplexity'];
const ALL_INDUSTRIES: Industry[] = ['saas', 'healthcare', 'ecommerce', 'fintech', 'education', 'creative', 'enterprise', 'restaurant', 'portfolio', 'ai'];
const ALL_AUTH: AuthState[] = ['guest', 'authenticated', 'admin', 'dashboard'];

export const COMPONENT_CATALOG: CatalogEntry[] = [
  // ── NAVBAR COMPONENTS ──────────────────────────────────────────────────────
  {
    id: 'Logo',
    name: 'Logo',
    sectionType: 'navbar',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 10,
  },
  {
    id: 'NavigationMenu',
    name: 'NavigationMenu',
    sectionType: 'navbar',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['NavigationMenu'],
    complexity: 'medium',
    dependencies: ['Logo'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'NavbarCTAButton',
    name: 'NavbarCTAButton',
    sectionType: 'navbar',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Button'],
    complexity: 'simple',
    dependencies: ['NavigationMenu'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 8,
  },
  {
    id: 'CommandPalette',
    name: 'CommandPalette',
    sectionType: 'navbar',
    supportedDNAs: ['linear', 'vercel'],
    supportedIndustries: ['saas', 'ai', 'enterprise'],
    supportedAuthStates: ['admin', 'dashboard'],
    recommendedShadcn: ['Command', 'CommandInput', 'CommandList'],
    complexity: 'complex',
    dependencies: ['Logo'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'AvatarMenu',
    name: 'AvatarMenu',
    sectionType: 'navbar',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['authenticated', 'admin', 'dashboard'],
    recommendedShadcn: ['Avatar', 'DropdownMenu'],
    complexity: 'medium',
    dependencies: ['Logo'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },

  // ── HERO COMPONENTS ────────────────────────────────────────────────────────
  {
    id: 'HeroBadge',
    name: 'HeroBadge',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Badge'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'Eyebrow',
    name: 'Eyebrow',
    sectionType: 'hero',
    supportedDNAs: ['notion', 'framer', 'cursor'],
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'HeroHeadline',
    name: 'HeroHeadline',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 10,
  },
  {
    id: 'HeroSupportingCopy',
    name: 'HeroSupportingCopy',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: ['HeroHeadline'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'PrimaryCTA',
    name: 'PrimaryCTA',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Button'],
    complexity: 'simple',
    dependencies: ['HeroHeadline'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 10,
  },
  {
    id: 'SecondaryCTA',
    name: 'SecondaryCTA',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Button'],
    complexity: 'simple',
    dependencies: ['PrimaryCTA'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 8,
  },
  {
    id: 'TrustRow',
    name: 'TrustRow',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Avatar'],
    complexity: 'simple',
    dependencies: ['PrimaryCTA'],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'AnnouncementBar',
    name: 'AnnouncementBar',
    sectionType: 'hero',
    supportedDNAs: ['stripe', 'vercel', 'linear'],
    supportedIndustries: ['saas', 'enterprise', 'ai'],
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Badge'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'EnterpriseProof',
    name: 'EnterpriseProof',
    sectionType: 'hero',
    supportedDNAs: ['stripe', 'vercel'],
    supportedIndustries: ['enterprise', 'fintech', 'saas'],
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Avatar', 'Badge'],
    complexity: 'medium',
    dependencies: ['TrustRow'],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'MotionBadge',
    name: 'MotionBadge',
    sectionType: 'hero',
    supportedDNAs: ['framer'],
    supportedIndustries: ['creative', 'saas', 'ai'],
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Badge'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'AnimatedVisual',
    name: 'AnimatedVisual',
    sectionType: 'hero',
    supportedDNAs: ['framer', 'cursor'],
    supportedIndustries: ['creative', 'saas', 'ai'],
    supportedAuthStates: ['guest'],
    recommendedShadcn: [],
    complexity: 'complex',
    dependencies: ['HeroHeadline'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 6,
  },
  {
    id: 'MinimalBadge',
    name: 'MinimalBadge',
    sectionType: 'hero',
    supportedDNAs: ['linear', 'vercel'],
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Badge'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'CTAGroup',
    name: 'CTAGroup',
    sectionType: 'hero',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Button'],
    complexity: 'simple',
    dependencies: ['HeroHeadline'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 9,
  },

  // ── FEATURES COMPONENTS ────────────────────────────────────────────────────
  {
    id: 'FeatureGrid',
    name: 'FeatureGrid',
    sectionType: 'features',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Card'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'FeatureCard',
    name: 'FeatureCard',
    sectionType: 'features',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Card'],
    complexity: 'simple',
    dependencies: ['FeatureGrid'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'StatsBlock',
    name: 'StatsBlock',
    sectionType: 'features',
    supportedDNAs: ['stripe', 'linear', 'vercel'],
    supportedIndustries: ['saas', 'enterprise', 'fintech'],
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Badge'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 7,
  },

  // ── PRICING COMPONENTS ─────────────────────────────────────────────────────
  {
    id: 'PricingHeader',
    name: 'PricingHeader',
    sectionType: 'pricing',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'PricingToggle',
    name: 'PricingToggle',
    sectionType: 'pricing',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Switch', 'Badge'],
    complexity: 'medium',
    dependencies: ['PricingHeader'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'PricingGrid',
    name: 'PricingGrid',
    sectionType: 'pricing',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Card'],
    complexity: 'medium',
    dependencies: ['PricingHeader'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'PricingCard',
    name: 'PricingCard',
    sectionType: 'pricing',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Card', 'Badge', 'Button'],
    complexity: 'medium',
    dependencies: ['PricingGrid'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 9,
  },
  {
    id: 'PricingFAQ',
    name: 'PricingFAQ',
    sectionType: 'pricing',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Accordion'],
    complexity: 'medium',
    dependencies: ['PricingGrid'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 6,
  },

  // ── TESTIMONIALS COMPONENTS ────────────────────────────────────────────────
  {
    id: 'TestimonialCard',
    name: 'TestimonialCard',
    sectionType: 'testimonials',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Card', 'Avatar'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'LogoCloud',
    name: 'LogoCloud',
    sectionType: 'testimonials',
    supportedDNAs: ['stripe', 'linear', 'vercel'],
    supportedIndustries: ['saas', 'enterprise', 'fintech'],
    supportedAuthStates: ['guest'],
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 7,
  },

  // ── DASHBOARD COMPONENTS ───────────────────────────────────────────────────
  {
    id: 'DashboardTabs',
    name: 'DashboardTabs',
    sectionType: 'dashboard',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ['saas', 'enterprise', 'fintech', 'ai'],
    supportedAuthStates: ['authenticated', 'admin', 'dashboard'],
    recommendedShadcn: ['Tabs', 'TabsList', 'TabsTrigger'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'DashboardFilters',
    name: 'DashboardFilters',
    sectionType: 'dashboard',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ['saas', 'enterprise', 'fintech', 'ai'],
    supportedAuthStates: ['authenticated', 'admin', 'dashboard'],
    recommendedShadcn: ['Select', 'Badge', 'Button'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'DataTable',
    name: 'DataTable',
    sectionType: 'dashboard',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ['saas', 'enterprise', 'fintech', 'ai'],
    supportedAuthStates: ['authenticated', 'admin', 'dashboard'],
    recommendedShadcn: ['Table', 'Badge', 'Button', 'Skeleton'],
    complexity: 'complex',
    dependencies: ['DashboardFilters'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },

  // ── STATS COMPONENTS ───────────────────────────────────────────────────────
  {
    id: 'MetricCard',
    name: 'MetricCard',
    sectionType: 'stats',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Card', 'Badge'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 7,
  },
  {
    id: 'ProgressBar',
    name: 'ProgressBar',
    sectionType: 'stats',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Progress'],
    complexity: 'simple',
    dependencies: ['MetricCard'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 6,
  },

  // ── FAQ COMPONENTS ─────────────────────────────────────────────────────────
  {
    id: 'FAQAccordion',
    name: 'FAQAccordion',
    sectionType: 'faq',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Accordion'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },

  // ── CTA COMPONENTS ─────────────────────────────────────────────────────────
  {
    id: 'CTAHeadline',
    name: 'CTAHeadline',
    sectionType: 'cta',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: [],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 9,
  },
  {
    id: 'CTAButton',
    name: 'CTAButton',
    sectionType: 'cta',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Button'],
    complexity: 'simple',
    dependencies: ['CTAHeadline'],
    requiresTrustSignal: false,
    requiresCTA: true,
    priority: 10,
  },
  {
    id: 'SocialProof',
    name: 'SocialProof',
    sectionType: 'cta',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['guest'],
    recommendedShadcn: ['Avatar'],
    complexity: 'simple',
    dependencies: ['CTAHeadline'],
    requiresTrustSignal: true,
    requiresCTA: false,
    priority: 7,
  },

  // ── FOOTER COMPONENTS ──────────────────────────────────────────────────────
  {
    id: 'FooterLinks',
    name: 'FooterLinks',
    sectionType: 'footer',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ALL_AUTH,
    recommendedShadcn: ['Separator'],
    complexity: 'simple',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 7,
  },

  // ── AUTH COMPONENTS ────────────────────────────────────────────────────────
  {
    id: 'AvatarUploader',
    name: 'AvatarUploader',
    sectionType: 'settings',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['authenticated', 'admin'],
    recommendedShadcn: ['Avatar', 'Button'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 6,
  },
  {
    id: 'SettingsTabs',
    name: 'SettingsTabs',
    sectionType: 'settings',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ALL_INDUSTRIES,
    supportedAuthStates: ['authenticated', 'admin'],
    recommendedShadcn: ['Tabs', 'Card'],
    complexity: 'medium',
    dependencies: [],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },
  {
    id: 'CRUDTable',
    name: 'CRUDTable',
    sectionType: 'dashboard',
    supportedDNAs: ALL_DNAS,
    supportedIndustries: ['saas', 'enterprise', 'fintech'],
    supportedAuthStates: ['admin'],
    recommendedShadcn: ['Table', 'Dialog', 'Button', 'Badge'],
    complexity: 'complex',
    dependencies: ['DataTable'],
    requiresTrustSignal: false,
    requiresCTA: false,
    priority: 8,
  },
];

// ── Lookup helpers ─────────────────────────────────────────────────────────────

export function getComponentsBySection(sectionType: SectionType): CatalogEntry[] {
  return COMPONENT_CATALOG.filter(c => c.sectionType === sectionType);
}

export function getComponentsForDNA(dna: DNABrand, sectionType: SectionType): CatalogEntry[] {
  return COMPONENT_CATALOG.filter(
    c => c.sectionType === sectionType && c.supportedDNAs.includes(dna)
  );
}

export function getComponentsForAuth(authState: AuthState, sectionType: SectionType): CatalogEntry[] {
  return COMPONENT_CATALOG.filter(
    c => c.sectionType === sectionType && c.supportedAuthStates.includes(authState)
  );
}

export function getComponentById(id: string): CatalogEntry | undefined {
  return COMPONENT_CATALOG.find(c => c.id === id);
}

export const CATALOG_SIZE = COMPONENT_CATALOG.length;
