// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/voxai-linear.tsx": () => import("../components/mockups/voxai-linear.tsx"),
  "./components/mockups/voxai-stripe.tsx": () => import("../components/mockups/voxai-stripe.tsx"),
  "./components/mockups/voxai-vercel.tsx": () => import("../components/mockups/voxai-vercel.tsx")
};
